### ISSUE TITLE
opening multiple source tabs and switching tabs...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1017]
Notes
======
opening multiple source tabs and switching tabs. then all cards disappeared.

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.2
build | 106
UDID | 5bea6cedc4cb419d
Android Release | 4.4.2
Android SDK | 19
Brand | Lenovo
Device | S8-50F
Stack trace
======
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.translationstudio.androidapp/com.door43.translationstudio.newui.translate.TargetTranslationActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2235)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2285)
	at android.app.ActivityThread.access$800(ActivityThread.java:138)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1236)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5064)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.door43.translationstudio.newui.translate.ChunkModeAdapter.<init>(ChunkModeAdapter.java:107)
	at com.door43.translationstudio.newui.translate.ChunkModeFragment.generateAdapter(ChunkModeFragment.java:21)
	at com.door43.translationstudio.newui.translate.ViewModeFragment.onCreateView(ViewModeFragment.java:85)
	at android.app.Fragment.performCreateView(Fragment.java:1700)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
	at android.app.BackStackRecord.run(BackStackRecord.java:684)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
	at android.app.Activity.performStart(Activity.java:5240)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2208)
	... 11 more

```
Log history
======
```java
11/19/15 12:12 PM  E/com.door43.translationstudio.service.BackupService: Failed to export the target translation uw-phm-aad
java.io.FileNotFoundException: /data/data/com.translationstudio.androidapp/files/translations/uw-phm-aad/.git/index.lock: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:409)
	at java.io.FileInputStream.<init>(FileInputStream.java:78)
	at java.io.FileInputStream.<init>(FileInputStream.java:105)
	at com.door43.util.Zip.zipSubFolder(Zip.java:215)
	at com.door43.util.Zip.zipSubFolder(Zip.java:210)
	at com.door43.util.Zip.zip(Zip.java:140)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:203)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:137)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:33)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:65)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
	at libcore.io.IoBridge.open(IoBridge.java:393)
	... 10 more

     
```

**Comment by neutrinog** [comment]
@jag3773 this might actually be our first negative impact of the chunk errors. Just an fyi.

**Comment by neutrinog** [comment]
might relate to https://github.com/unfoldingWord-dev/ts-desktop/issues/142
