### ISSUE TITLE
scrolling down through OBS.

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1018]
Notes
======
scrolling down through OBS.

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 104
UDID | b933f746e4afb0dd
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Stack trace
======
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.scrollToPosition(int)' on a null object reference
	at com.door43.translationstudio.newui.translate.ViewModeFragment.onScrollProgressUpdate(ViewModeFragment.java:300)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity$1.onProgressChanged(TargetTranslationActivity.java:133)
	at com.door43.widget.VerticalSeekBar.onTouchEvent(VerticalSeekBar.java:62)
	at android.view.View.dispatchTouchEvent(View.java:8471)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.dispatchTouchEvent(TargetTranslationActivity.java:347)
	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
	at android.view.View.dispatchPointerEvent(View.java:8666)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5868)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5920)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```
Log history
======
```java
11/20/15 05:46  I/com.door43.translationstudio.service.BackupService: Backups running every 5 minute/s
11/20/15 05:46  I/com.door43.translationstudio.service.BackupService: Backups running every 5 minute/s
11/20/15 05:46  I/com.door43.translationstudio.service.BackupService: starting backup service
11/20/15 05:46  W/com.door43.translationstudio.newui.translate.ChunkModeFragment: The gesture dectector was not initialized so the touch was not handled
11/20/15 05:46  W/com.door43.translationstudio.newui.translate.ChunkModeFragment: The gesture dectector was not initialized so the touch was not handled
11/20/15 05:45  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
11/20/15 05:45  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord fruit in gen-en-ulb
11/20/15 05:45  I/com.door43.translationstudio.service.BackupService: Backups running every 5 minute/s
11/20/15 05:45  I/com.door43.translationstudio.service.BackupService: starting backup service
10/8/15 11:46  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 11:46  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord fruit in gen-en-ulb
10/8/15 11:46  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:45  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:45  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:45  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:45  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:45  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:45  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:32  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:32  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:32  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:32  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:23  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:23  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:23  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:23  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:15  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord fruit in gen-en-ulb
10/8/15 11:15  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 11:15  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord fruit in gen-en-ulb
10/8/15 11:15  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord imageofgod in gen-en-ulb
10/8/15 11:15  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord fruit in gen-en-ulb
10/8/15 11:15  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 11:14  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 11:13  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord seed in gen-en-ulb
10/8/15 11:13  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 11:13  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord fruit in gen-en-ulb
10/8/15 11:13  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 11:12  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord seed in gen-en-ulb
10/8/15 11:12  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 11:12  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord fruit in gen-en-ulb
10/8/15 11:12  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 11:12  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 10:57  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 10:55  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 10:55  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 10:53  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 10:51  I/com.door43.translationstudio.service.BackupService: Backups running every 5 minute/s
10/8/15 10:51  I/com.door43.translationstudio.service.BackupService: starting backup service
10/8/15 10:51  I/com.door43.translationstudio.service.BackupService: stopping backup service
10/8/15 10:50  I/com.door43.translationstudio.service.BackupService: Backups running every 5 minute/s
10/8/15 10:50  I/com.door43.translationstudio.service.BackupService: starting backup service
10/8/15 10:50  I/com.door43.translationstudio.service.BackupService: stopping backup service
10/8/15 10:50  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/8/15 10:43  I/com.door43.translationstudio.service.BackupService: Backups running every 5 minute/s
10/8/15 10:43  I/com.door43.translationstudio.service.BackupService: starting backup service
10/6/15 22:11  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/6/15 22:09  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/6/15 22:07  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/6/15 22:05  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/6/15 22:03  I/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Committed the latest translation for uw-gen-pt-br
10/6/15 22:02  I/com.door43.translationstudio.service.BackupService: Backups running every 5 minute/s
10/6/15 22:02  I/com.door43.translationstudio.service.BackupService: starting backup service
10/6/15 22:02  I/com.door43.translationstudio.service.BackupService: stopping backup service
10/6/15 22:00  W/com.door43.translationstudio.service.BackupService: Failed to read commit hash
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.core.TargetTranslation.commitHash(TargetTranslation.java:499)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:110)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:34)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:66)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

10/6/15 22:00  W/com.door43.translationstudio.service.BackupService: Failed to read commit hash
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.core.TargetTranslation.commitHash(TargetTranslation.java:499)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:110)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:34)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:66)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

10/6/15 22:00  I/com.door43.translationstudio.service.BackupService: Backups running every 5 minute/s
10/6/15 22:00  I/com.door43.translationstudio.service.BackupService: Backups running every 5 minute/s
10/6/15 22:00  I/com.door43.translationstudio.service.BackupService: starting backup service
10/6/15 22:00  I/com.door43.translationstudio.core.Indexer: indexing source for obs-pt-br-obs
10/6/15 22:00  I/com.door43.translationstudio.core.Indexer: indexing source for obs-pt-br-obs
     
```

**Comment by neutrinog** [comment]
I think this was due to the chunk bugs.
