### ISSUE TITLE
stuff

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1021]
Notes
======
stuff

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.2
build | 107
UDID | d757cfb5eb3ededd
Android Release | 5.1.1
Android SDK | 22
Brand | lge
Device | d850
Stack trace
======
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.door43.translationstudio.newui.translate.ReviewModeAdapter.getItemPosition(ReviewModeAdapter.java:261)
	at com.door43.translationstudio.newui.translate.ViewModeFragment.scrollToFrame(ViewModeFragment.java:190)
	at com.door43.translationstudio.newui.translate.ReviewModeFragment$6.onClick(ReviewModeFragment.java:272)
	at android.view.View.performClick(View.java:4781)
	at android.view.View$PerformClick.run(View.java:19873)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5281)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

```
Log history
======
```java
11/24/15 1:01 AM  E/com.door43.translationstudio.service.NetworkService$1: failed to accept the receiver socket
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
	at java.net.ServerSocket.implAccept(ServerSocket.java:216)
	at java.net.ServerSocket.accept(ServerSocket.java:140)
	at com.door43.translationstudio.service.NetworkService$1.run(NetworkService.java:175)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
	at libcore.io.Posix.accept(Native Method)
	at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
	... 4 more

11/24/15 1:00 AM  E/com.door43.translationstudio.service.NetworkService$1: failed to accept the receiver socket
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
	at java.net.ServerSocket.implAccept(ServerSocket.java:216)
	at java.net.ServerSocket.accept(ServerSocket.java:140)
	at com.door43.translationstudio.service.NetworkService$1.run(NetworkService.java:175)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
	at libcore.io.Posix.accept(Native Method)
	at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
	... 4 more

11/24/15 12:59 AM  E/com.door43.translationstudio.service.NetworkService$1: failed to accept the receiver socket
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
	at java.net.ServerSocket.implAccept(ServerSocket.java:216)
	at java.net.ServerSocket.accept(ServerSocket.java:140)
	at com.door43.translationstudio.service.NetworkService$1.run(NetworkService.java:175)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
	at libcore.io.Posix.accept(Native Method)
	at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
	... 4 more

11/24/15 12:57 AM  E/com.door43.translationstudio.service.NetworkService$1: failed to accept the receiver socket
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
	at java.net.ServerSocket.implAccept(ServerSocket.java:216)
	at java.net.ServerSocket.accept(ServerSocket.java:140)
	at com.door43.translationstudio.service.NetworkService$1.run(NetworkService.java:175)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
	at libcore.io.Posix.accept(Native Method)
	at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
	... 4 more

11/24/15 12:55 AM  E/com.door43.translationstudio.service.NetworkService$1: failed to accept the receiver socket
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
	at java.net.ServerSocket.implAccept(ServerSocket.java:216)
	at java.net.ServerSocket.accept(ServerSocket.java:140)
	at com.door43.translationstudio.service.NetworkService$1.run(NetworkService.java:175)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
	at libcore.io.Posix.accept(Native Method)
	at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
	... 4 more

11/24/15 12:55 AM  E/com.door43.translationstudio.service.NetworkService$1: failed to accept the receiver socket
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
	at java.net.ServerSocket.implAccept(ServerSocket.java:216)
	at java.net.ServerSocket.accept(ServerSocket.java:140)
	at com.door43.translationstudio.service.NetworkService$1.run(NetworkService.java:175)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
	at libcore.io.Posix.accept(Native Method)
	at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
	... 4 more

11/24/15 12:54 AM  E/com.door43.translationstudio.service.NetworkService$1: failed to accept the receiver socket
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
	at java.net.ServerSocket.implAccept(ServerSocket.java:216)
	at java.net.ServerSocket.accept(ServerSocket.java:140)
	at com.door43.translationstudio.service.NetworkService$1.run(NetworkService.java:175)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
	at libcore.io.Posix.accept(Native Method)
	at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
	... 4 more

11/24/15 12:53 AM  E/com.door43.translationstudio.service.NetworkService$1: failed to accept the receiver socket
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
	at java.net.ServerSocket.implAccept(ServerSocket.java:216)
	at java.net.ServerSocket.accept(ServerSocket.java:140)
	at com.door43.translationstudio.service.NetworkService$1.run(NetworkService.java:175)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
	at libcore.io.Posix.accept(Native Method)
	at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
	... 4 more

11/24/15 12:46 AM  E/com.door43.translationstudio.service.NetworkService$1: failed to accept the receiver socket
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
	at java.net.ServerSocket.implAccept(ServerSocket.java:216)
	at java.net.ServerSocket.accept(ServerSocket.java:140)
	at com.door43.translationstudio.service.NetworkService$1.run(NetworkService.java:175)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
	at libcore.io.Posix.accept(Native Method)
	at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

11/23/15 8:09 PM  E/com.door43.translationstudio.service.BroadcastService$1: Failed to send the broadcast packet
java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
	at libcore.io.IoBridge.sendto(IoBridge.java:515)
	at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:184)
	at java.net.DatagramSocket.send(DatagramSocket.java:305)
	at com.door43.translationstudio.service.BroadcastService$1.run(BroadcastService.java:116)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: android.system.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.sendtoBytes(Native Method)
	at libcore.io.Posix.sendto(Posix.java:206)
	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
	at libcore.io.IoBridge.sendto(IoBridge.java:513)
	... 4 more

     
```

**Comment by neutrinog** [comment]
Clicked on an example in a word.

**Comment by neutrinog** [comment]
I think this was due to the chunk bugs.
