### ISSUE TITLE
I was trying to open Hindi obs as source text.

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1038]
Notes
======
I was trying to open Hindi obs as source text.

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.2
build | 106
UDID | 3a0726915992729e
Android Release | 4.4.4
Android SDK | 19
Brand | Dell
Device | Venue7
Stack trace
======
```java
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.door43.translationstudio.newui.translate.ChunkModeAdapter.<init>(ChunkModeAdapter.java:107)
	at com.door43.translationstudio.newui.translate.ChunkModeFragment.generateAdapter(ChunkModeFragment.java:21)
	at com.door43.translationstudio.newui.translate.ViewModeFragment.onCreateView(ViewModeFragment.java:85)
	at android.app.Fragment.performCreateView(Fragment.java:1700)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
	at android.app.BackStackRecord.run(BackStackRecord.java:684)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5045)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
	at dalvik.system.NativeStart.main(Native Method)

```
Log history
======
```java
11/26/15 9:21 PM  W/com.door43.translationstudio.core.Downloader: Failed to fetch the catalog from https://api.unfoldingword.org/obs/txt/1/pa/CQ-pa.json
11/26/15 9:21 PM  W/com.door43.translationstudio.core.Downloader: Failed to fetch the catalog from https://api.unfoldingword.org/obs/txt/1/pa/tN-pa.json
11/26/15 9:20 PM  W/com.door43.translationstudio.core.Downloader: Failed to fetch the catalog from https://api.unfoldingword.org/obs/txt/1/pa/tw_cat-pa.json
11/26/15 9:20 PM  W/com.door43.translationstudio.core.Downloader: Failed to fetch the catalog from https://api.unfoldingword.org/obs/txt/1/pa/kt-pa.json
11/26/15 9:20 PM  W/com.door43.translationstudio.core.Downloader: Failed to fetch the catalog from https://api.unfoldingword.org/obs/txt/1/pa/obs-pa.json?date_modified=20151028
     
```

**Comment by neutrinog** [comment]
this is probably the chunk bug
