### ISSUE TITLE
starting a new translation from English to Fren...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1042]
Notes
======
starting a new translation from English to French.

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.2
build | 106
UDID | 9a78ca4de94ff979
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Stack trace
======
```java
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:168)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:667)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /data/data/com.translationstudio.androidapp/files/translations/uw-obs-fr/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1053)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 2 more

```
Log history
======
```java
12/6/15 8:59 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:655)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:634)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:108)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:33)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:65)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /data/data/com.translationstudio.androidapp/files/translations/uw-obs-fr/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1053)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

     
```

**Comment by neutrinog** [comment]
This is probably a race with the backup service.
