### ISSUE TITLE
Crash on Android 4.1.1 dealing with Bible translations (not OBS)

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/ts-android#1126]
Crash Exception importing mrk-kus. Stack dump:

	12-14 12:46:13.770 2041-2044/com.translationstudio.androidapp D/dalvikvm: GC_CONCURRENT freed 368K, 23% free 7208K/9287K, paused 10ms+1ms, total 14ms
	12-14 12:46:13.770 2041-2041/com.translationstudio.androidapp E/AndroidRuntime: FATAL EXCEPTION: main
	                                                                                java.lang.IndexOutOfBoundsException
	                                                                                    at android.graphics.Paint.getTextRunAdvances(Paint.java:1731)
	                                                                                    at android.graphics.Paint.getTextRunAdvances(Paint.java:1704)
	                                                                                    at android.text.MeasuredText.addStyleRun(MeasuredText.java:164)
	                                                                                    at android.text.MeasuredText.addStyleRun(MeasuredText.java:204)
	                                                                                    at android.text.StaticLayout.generate(StaticLayout.java:281)
	                                                                                    at android.text.StaticLayout.<init>(StaticLayout.java:140)
	                                                                                    at android.text.StaticLayout.<init>(StaticLayout.java:80)
	                                                                                    at android.text.StaticLayout.<init>(StaticLayout.java:59)
	                                                                                    at android.widget.TextView.makeSingleLayout(TextView.java:5901)
	                                                                                    at android.widget.TextView.makeNewLayout(TextView.java:5741)
	                                                                                    at android.widget.TextView.onMeasure(TextView.java:6098)
	                                                                                    at android.view.View.measure(View.java:15172)
	                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
	                                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
	                                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
	                                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
	                                                                                    at android.view.View.measure(View.java:15172)
	                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
	                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	                                                                                    at android.support.v7.widget.CardView.onMeasure(CardView.java:196)
	                                                                                    at android.view.View.measure(View.java:15172)
	                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
	                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	                                                                                    at android.view.View.measure(View.java:15172)
	                                                                                    at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:6699)
	                                                                                    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
	                                                                                    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1327)
	                                                                                    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:556)
	                                                                                    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2713)
	                                                                                    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3011)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
	                                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
	                                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
	                                                                                    at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1638)
	                                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1422)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1009)
	                                                                                    at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:719)
	                                                                                    at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:733)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
	                                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
	                                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)

                                                                                	at android.vi

**Comment by PhotoNomad0** [comment]
Other observations:

 See crash 
	• creating new Mark kus on 3.1.0-beta.1, 
	• also see this on 3.0.2 (even with multidex enabled), 
	• also see the problem creating NT bible translations in many languages, but not on OBS.  
	• Does not matter which source translation selected.  
	• App also fails trying to submit problem report.


Do not see this issue on Android 4.2.2.

**Comment by PhotoNomad0** [comment]
Most of the time there is no stack trace captured.

**Comment by PhotoNomad0** [comment]
Do not see this problem on 4.0.3 API 15 in Android Virtual Device Manager.  

But do see the problem on 4.1.2 API 16 in Android Virtual Device Manager. 
Could this be just a 4.1.x issue?  Since I see this on both AVD and Genymotion emulators.

**Comment by neutrinog** [comment]
the stack trace sure isn't helpful. :(

**Comment by PhotoNomad0** [comment]
Since it is a new translation, I am guessing that there is an drawing the first page.

I see one call to ReadModeAdapter::onBindViewHolder() that completes without error and then see the crash before the second chunk is bound.

It looks like the stack dump is related to applying a style which makes me wonder if there is a style error that is being trapped in other android versions.  I'll keep digging in unless there is a higher priority.

**Comment by PhotoNomad0** [comment]
It is confusing that I can do a OBS translation without crash.  Seems like all the Bilbe is crashing.  Some formatting thing?
