### ISSUE TITLE
tried to update Jude

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1211]
Notes
======
tried to update Jude

Environment
======
Environment Key | Value
:----: | :----:
version | 3.1.0
build | 110
UDID | dd19773da22f5f
Android Release | 5.0
Android SDK | 21
Brand | Verizon
Device | kltevzw
Stack trace
======
```java
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.door43.translationstudio.core.Indexer.indexQuestions(Indexer.java:686)
	at com.door43.translationstudio.core.Downloader.downloadCheckingQuestions(Downloader.java:211)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:270)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:220)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```

**Comment by neutrinog** [comment]
related to https://github.com/unfoldingWord-dev/ts-android/issues/1212

**Comment by neutrinog** [comment]
this is a bug in the api. The new checking questions update formats the `ref` fields like  `1:1` instead of `01-01`.

**Comment by jag3773** [comment]
Fixed
