### ISSUE TITLE
I was importing from Internet.

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1352]
Notes
======
I was importing from Internet.

Environment
======
Environment Key | Value
:----: | :----:
version | 5.0
build | 117
UDID | f97146a01c2c926
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Stack trace
======
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.translationstudio.androidapp/com.door43.translationstudio.newui.translate.TargetTranslationActivity}: java.security.InvalidParameterException: a valid target translation id is required
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
	at android.app.ActivityThread.access$800(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: java.security.InvalidParameterException: a valid target translation id is required
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onCreate(TargetTranslationActivity.java:78)
	at android.app.Activity.performCreate(Activity.java:5971)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	... 10 more

```

**Comment by neutrinog** [comment]
added proper error handling so that an invalid target translation id (likely by starting the app after updating from an older version) will not crash the app. 

You should now be able to run an older version of the app, open a target translation for editing, close it, update the app, and open again without an error.

**Comment by cckozie** [comment]
QA checked version 5.0 to 6.0 build 118. The app did not crash and I did not get an error, but the source translations were no longer associated with my projects.
