### ISSUE TITLE
Looking at the first TN on matt 5:33

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1358]
Notes
======
Looking at the first TN on matt 5:33

Environment
======
Environment Key | Value
:----: | :----:
version | 3.3
build | 113
UDID | e7848e883731e8e0
Android Release | 4.1.2
Android SDK | 16
Brand | verizon
Device | ADR930L
Stack trace
======
```java
java.lang.NullPointerException
	at com.door43.translationstudio.newui.translate.ReviewModeFragment$11.onPreprocess(ReviewModeFragment.java:487)
	at com.door43.translationstudio.rendering.HtmlRenderer.renderLink(HtmlRenderer.java:105)
	at com.door43.translationstudio.rendering.HtmlRenderer.renderPassageLink(HtmlRenderer.java:43)
	at com.door43.translationstudio.rendering.HtmlRenderer.render(HtmlRenderer.java:30)
	at com.door43.translationstudio.newui.translate.ReviewModeFragment.renderTranslationNote(ReviewModeFragment.java:519)
	at com.door43.translationstudio.newui.translate.ReviewModeFragment.onTranslationNoteClick(ReviewModeFragment.java:165)
	at com.door43.translationstudio.newui.translate.ReviewModeAdapter$20.onClick(ReviewModeAdapter.java:1305)
	at android.view.View.performClick(View.java:4084)
	at android.view.View$PerformClick.run(View.java:16966)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4856)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
	at dalvik.system.NativeStart.main(Native Method)

```
Log history
======
```java
3/21/16 3:26 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:bible:notes:isa:66:01|66:1]] and Psalm [[:en:bible:notes:psa:148:001
3/10/16 4:40 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation uw-dan-aad
3/10/16 4:40 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation uw-obs-aad
3/10/16 4:40 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation uw-act-aad
3/10/16 4:40 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation uw-jhn-aad
     
```

**Comment by neutrinog** [comment]
this bug actually occurs in the note `swear not ... by heaven ... the throne of God...` not the first note.
