### ISSUE TITLE
When attempting to setup a pseudo name for my g...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1398]
Notes
======
When attempting to setup a pseudo name for my group to identify my backup. This is at the backup tab of the using the backup to a friend option.

Environment
======
Environment Key | Value
:----: | :----:
version | 3.3
build | 113
UDID | cf50cfa8152180f7
Android Release | 4.2.2
Android SDK | 17
Brand | Lenovo
Device | A10
Stack trace
======
```java
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.apache.harmony.xnet.provider.jsse.OpenSSLRSAPrivateKey)
	at android.os.Parcel.writeSerializable(Parcel.java:1279)
	at android.os.Parcel.writeValue(Parcel.java:1233)
	at android.os.Parcel.writeMapInternal(Parcel.java:591)
	at android.os.Bundle.writeToParcel(Bundle.java:1627)
	at android.os.Parcel.writeBundle(Parcel.java:605)
	at android.content.Intent.writeToParcel(Intent.java:6660)
	at android.app.ActivityManagerProxy.bindService(ActivityManagerNative.java:2729)
	at android.app.ContextImpl.bindService(ContextImpl.java:1431)
	at android.app.ContextImpl.bindService(ContextImpl.java:1407)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
	at com.door43.translationstudio.newui.ShareWithPeerDialog.onStart(ShareWithPeerDialog.java:289)
	at android.app.Fragment.performStart(Fragment.java:1719)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:913)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
	at android.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.io.NotSerializableException: org.apache.harmony.xnet.provider.jsse.OpenSSLKey
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1364)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
	at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:979)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:368)
	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1074)
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1404)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
	at android.os.Parcel.writeSerializable(Parcel.java:1274)
	... 25 more

```
Log history
======
```java
3/29/16 2:27 PM  E/com.door43.translationstudio.newui.ShareWithPeerDialog: Failed to initialize the server service
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.apache.harmony.xnet.provider.jsse.OpenSSLRSAPrivateKey)
	at android.os.Parcel.writeSerializable(Parcel.java:1279)
	at android.os.Parcel.writeValue(Parcel.java:1233)
	at android.os.Parcel.writeMapInternal(Parcel.java:591)
	at android.os.Bundle.writeToParcel(Bundle.java:1627)
	at android.os.Parcel.writeBundle(Parcel.java:605)
	at android.content.Intent.writeToParcel(Intent.java:6660)
	at android.app.ActivityManagerProxy.startService(ActivityManagerNative.java:2659)
	at android.app.ContextImpl.startServiceAsUser(ContextImpl.java:1366)
	at android.app.ContextImpl.startService(ContextImpl.java:1353)
	at android.content.ContextWrapper.startService(ContextWrapper.java:450)
	at com.door43.translationstudio.newui.ShareWithPeerDialog.initializeService(ShareWithPeerDialog.java:319)
	at com.door43.translationstudio.newui.ShareWithPeerDialog.onStart(ShareWithPeerDialog.java:283)
	at android.app.Fragment.performStart(Fragment.java:1719)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:913)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
	at android.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.io.NotSerializableException: org.apache.harmony.xnet.provider.jsse.OpenSSLKey
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1364)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
	at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:979)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:368)
	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1074)
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1404)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
	at android.os.Parcel.writeSerializable(Parcel.java:1274)
	... 26 more

     
```

**Comment by cckozie** [comment]
Tested on Android 5.1.1
