### ISSUE TITLE
I was typing

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1403]
Notes
======
I was typing

Environment
======
Environment Key | Value
:----: | :----:
version | 3.3
build | 113
UDID | a97894a9c17430f4
Android Release | 4.2.2
Android SDK | 17
Brand | Lenovo
Device | A10
Stack trace
======
```java
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=5 (# cursors opened by this proc=5)
	at android.database.CursorWindow.<init>(CursorWindow.java:104)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
	at com.door43.translationstudio.core.IndexerSQLiteHelper.getSourceLanguage(IndexerSQLiteHelper.java:1160)
	at com.door43.translationstudio.core.Indexer.getSourceLanguage(Indexer.java:1060)
	at com.door43.translationstudio.core.Library.getPreferredSourceLanguage(Library.java:432)
	at com.door43.translationstudio.core.Library.getTranslationProgress(Library.java:498)
	at com.door43.translationstudio.newui.home.TargetTranslationAdapter$1.run(TargetTranslationAdapter.java:109)
	at com.door43.util.tasks.ThreadableUI$1.run(ThreadableUI.java:27)

```

**Comment by neutrinog** [comment]
dup of #1392
