### ISSUE TITLE
rotated app while viewing merge conflicts dialo...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1440]
Notes
======
rotated app while viewing merge conflicts dialog after trying to back up to door43.

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 123
UDID | f6b1fd4623e9d222
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Stack trace
======
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.translationstudio.androidapp/com.door43.translationstudio.newui.translate.TargetTranslationActivity}: java.security.InvalidParameterException: a valid target translation id is required
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4118)
	at android.app.ActivityThread.access$900(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: java.security.InvalidParameterException: a valid target translation id is required
	at com.door43.translationstudio.newui.translate.ViewModeFragment.onCreateView(ViewModeFragment.java:70)
	at android.app.Fragment.performCreateView(Fragment.java:2069)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:899)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1072)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1054)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1895)
	at android.app.Activity.performCreateCommon(Activity.java:5966)
	at android.app.Activity.performCreate(Activity.java:5973)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	... 11 more

```
Log history
======
```java
4/20/16 3:50 AM  E/TargetTranslationActivity: A valid target translation id is required. Received 'aa_1jn_text_reg' but the translation could not be found
4/20/16 3:50 AM  E/com.door43.translationstudio.tasks.PullTargetTranslationTask: git@git.door43.org:joel/aa_1jn_text_reg.git: Auth fail
org.eclipse.jgit.api.errors.TransportException: git@git.door43.org:joel/aa_1jn_text_reg.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:261)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.pull(PullTargetTranslationTask.java:141)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.start(PullTargetTranslationTask.java:78)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.TransportException: git@git.door43.org:joel/aa_1jn_text_reg.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 7 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 14 more

     

```

**Comment by neutrinog** [comment]
cannot reproduce this.
