### ISSUE TITLE
attempting to publish while logged in locally. ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1443]
Notes
======
attempting to publish while logged in locally. could not create new door43 account

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 123
UDID | f710314c4d27668b
Android Release | 4.4.2
Android SDK | 19
Brand | rockchip
Device | rk292x
Log history
======
```java
4/20/16 1:41 PM  W/com.door43.translationstudio.tasks.LoginDoor43Task: gogs api responded with 422: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/admin/users
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:186)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createUser(GogsAPI.java:193)
	at com.door43.translationstudio.tasks.RegisterDoor43Task.start(RegisterDoor43Task.java:50)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

4/20/16 1:37 PM  W/com.door43.translationstudio.tasks.LoginDoor43Task: gogs api responded with 422: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/admin/users
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:186)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createUser(GogsAPI.java:193)
	at com.door43.translationstudio.tasks.RegisterDoor43Task.start(RegisterDoor43Task.java:50)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

4/20/16 1:25 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation ena_jud_text_reg
4/20/16 1:25 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation ena_jud_text_reg
4/20/16 11:43 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_obs_text_obs
4/20/16 11:43 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_obs_text_obs
     

```

**Comment by cckozie** [comment]
See #1447
