### ISSUE TITLE
Trying to create a new account during publish p...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1447]
Notes
======
Trying to create a new account during publish process

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 126
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Log history
======
```java
4/21/16 8:34 PM  W/com.door43.translationstudio.tasks.LoginDoor43Task: gogs api responded with 422: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/admin/users
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createUser(GogsAPI.java:193)
	at com.door43.translationstudio.tasks.RegisterDoor43Task.start(RegisterDoor43Task.java:50)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

4/21/16 8:34 PM  W/com.door43.translationstudio.tasks.LoginDoor43Task: gogs api responded with 422: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/admin/users
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createUser(GogsAPI.java:193)
	at com.door43.translationstudio.tasks.RegisterDoor43Task.start(RegisterDoor43Task.java:50)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

4/21/16 8:30 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_jud_text_reg
4/21/16 8:30 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_jud_text_reg
     

```

**Comment by cckozie** [comment]
![create_profile](https://cloud.githubusercontent.com/assets/8171759/14729206/677fe18c-0801-11e6-9974-bbb8d92c2e46.png)

**Comment by neutrinog** [comment]
@cckozie I cannot reproduce this error :( I've tried on 5.1 and 6.0.
