### ISSUE TITLE
launching ap.

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1463]
Notes
======
launching ap.

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 128
UDID | 89283eee2c5b1605
Android Release | 4.4.2
Android SDK | 19
Brand | samsung
Device | degaswifiue
Stack trace
======
```java
android.view.InflateException: Binary XML file line #3: Error inflating class java.lang.reflect.Constructor
	at android.preference.GenericInflater.createItem(GenericInflater.java:397)
	at android.preference.GenericInflater.onCreateItem(GenericInflater.java:417)
	at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:428)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
	at android.preference.GenericInflater.inflate(GenericInflater.java:326)
	at android.preference.GenericInflater.inflate(GenericInflater.java:263)
	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
	at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:485)
	at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:444)
	at com.door43.translationstudio.tasks.UpdateAppTask.performUpdates(UpdateAppTask.java:97)
	at com.door43.translationstudio.tasks.UpdateAppTask.start(UpdateAppTask.java:69)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.preference.GenericInflater.createItem(GenericInflater.java:383)
	... 14 more
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:200)
	at android.os.Handler.<init>(Handler.java:114)
	at android.sec.clipboard.ClipboardExManager$1.<init>(ClipboardExManager.java:118)
	at android.sec.clipboard.ClipboardExManager.<init>(ClipboardExManager.java:118)
	at android.app.ContextImpl$11.createService(ContextImpl.java:475)
	at android.app.ContextImpl$ServiceFetcher.getService(ContextImpl.java:367)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:2090)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:552)
	at android.widget.EditText.<init>(EditText.java:81)
	at android.widget.EditText.<init>(EditText.java:75)
	at android.preference.EditTextPreference.<init>(EditTextPreference.java:56)
	at android.preference.EditTextPreference.<init>(EditTextPreference.java:72)
	... 17 more

```
Log history
======
```java
4/14/16 11:42 AM  E/com.door43.translationstudio.newui.home.RestoreFromCloudDialog: Failed to open the online backup
4/14/16 11:42 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation tpi_luk_text_reg
4/14/16 11:42 AM  E/com.door43.translationstudio.newui.home.RestoreFromCloudDialog: Failed to open the online backup
4/14/16 11:42 AM  E/com.door43.translationstudio.newui.home.RestoreFromCloudDialog: Failed to open the online backup
4/14/16 11:42 AM  E/com.door43.translationstudio.tasks.GetCloudBackupsTask: Failed to retrieve the list of backups on the server
com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.door43.translationstudio.git.SSHSession.openSession(SSHSession.java:55)
	at com.door43.translationstudio.tasks.GetCloudBackupsTask.start(GetCloudBackupsTask.java:32)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

4/14/16 11:41 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation uw-mat-tpi
4/14/16 11:41 AM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 4 inuw-mat-tpi
     

```

**Comment by neutrinog** [comment]
added looper prepare to update task
