### ISSUE TITLE
Trying to log in

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1464]
Notes
======
Trying to log in

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 128
UDID | 305a12d283d600d5
Android Release | 5.0
Android SDK | 21
Brand | TECNO
Device | TECNO 8H
Stack trace
======
```java
java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.unfoldingword.gogsclient.User.fullName' on a null object reference
	at com.door43.translationstudio.tasks.LoginDoor43Task.start(LoginDoor43Task.java:85)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```
Log history
======
```java
5/11/16 10:48 AM  W/com.door43.translationstudio.tasks.LoginDoor43Task: gogs api responded with 401: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/users/aaserhna/tokens
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createToken(GogsAPI.java:399)
	at com.door43.translationstudio.tasks.LoginDoor43Task.start(LoginDoor43Task.java:74)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

5/5/16 7:44 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation cache
5/5/16 4:53 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation cache
5/5/16 1:40 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation cache
4/29/16 2:45 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation oso_2pe_text_reg
4/29/16 2:45 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation oso_2pe_text_reg
4/29/16 2:42 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation cache
4/27/16 6:48 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation cache
4/18/16 11:40 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation oso_mrk_text_reg
4/18/16 11:40 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation oso_mrk_text_reg
4/18/16 11:39 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation cache
4/15/16 10:08 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation cache
4/13/16 7:25 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation uw-eph-oso
4/13/16 7:25 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation cache
4/13/16 7:24 AM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 4 inuw-eph-oso
     

```

**Comment by neutrinog** [comment]
this was literally a one line fix.
