### ISSUE TITLE
rotated device while the merge conflict dialog ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1469]
Notes
======
rotated device while the merge conflict dialog was open. this was right after trying to publish.

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 128
UDID | 29fc019efc78c5c1
Android Release | 5.1.1
Android SDK | 22
Brand | OnePlus
Device | OnePlus
Stack trace
======
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.translationstudio.androidapp/com.door43.translationstudio.newui.publish.PublishActivity}: java.security.InvalidParameterException: a valid target translation id is required
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2362)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2424)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3991)
	at android.app.ActivityThread.access$1000(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:139)
	at android.app.ActivityThread.main(ActivityThread.java:5298)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
Caused by: java.security.InvalidParameterException: a valid target translation id is required
	at com.door43.translationstudio.newui.publish.PublishActivity.onCreate(PublishActivity.java:66)
	at android.app.Activity.performCreate(Activity.java:6072)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
	... 11 more

```
Log history
======
```java
5/11/16 8:56 AM  E/com.door43.translationstudio.tasks.PullTargetTranslationTask: git@git.door43.org:joel/aa_1jn_text_reg.git: Auth fail
org.eclipse.jgit.api.errors.TransportException: git@git.door43.org:joel/aa_1jn_text_reg.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:261)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.pull(PullTargetTranslationTask.java:141)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.start(PullTargetTranslationTask.java:78)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.TransportException: git@git.door43.org:joel/aa_1jn_text_reg.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 7 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 14 more

5/11/16 8:51 AM  W/com.door43.translationstudio.tasks.LoginDoor43Task: gogs api responded with 401: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/users/joel/tokens
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createToken(GogsAPI.java:419)
	at com.door43.translationstudio.tasks.LoginDoor43Task.start(LoginDoor43Task.java:74)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

     

```

**Comment by neutrinog** [comment]
related to #1470 because when the manifest becomes corrupt the activity is no longer able to find it so it throws an exception.
