### ISSUE TITLE
I was attempting to add a new project i.e. Roma...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1475]
Notes
======
I was attempting to add a new project i.e. Romans. It was very slow, moving from step to step: Why is there now 2 ULB and UDB texts to choose from instead of 1 each?

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 128
UDID | 8b73aeb8a08dd653
Android Release | 4.2.2
Android SDK | 17
Brand | Lenovo
Device | A10
Stack trace
======
```java
java.lang.IllegalStateException: Activity has been destroyed
	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1333)
	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
	at android.app.BackStackRecord.commit(BackStackRecord.java:574)
	at android.app.DialogFragment.show(DialogFragment.java:230)
	at com.door43.translationstudio.dialogs.CustomAlertDialog.show(CustomAlertDialog.java:259)
	at com.door43.translationstudio.DeveloperToolsActivity$9$1.onPostExecute(DeveloperToolsActivity.java:238)
	at com.door43.util.tasks.ThreadableUI$1$1.run(ThreadableUI.java:32)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)

```
Log history
======
```java
5/12/16 7:16 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation ema-x-ora_rom_text_reg
5/12/16 7:16 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation ema-x-ora_rom_text_reg
     

```

**Comment by neutrinog** [comment]
cannot reproduce. Also the stack trace is from the developer tools. Users' should not be in there anyway.
