### ISSUE TITLE
i was trying to open it

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1481]
Notes
======
i was trying to open it

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 128
UDID | 8053527b9ff22a24
Android Release | 5.1
Android SDK | 22
Brand | INFINIX
Device | INFINIX-X551
Stack trace
======
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.door43.translationstudio.core.SourceTranslation.getId()' on a null object reference
	at com.door43.translationstudio.newui.translate.FirstTabFragment.onConfirmTabsDialog(FirstTabFragment.java:116)
	at com.door43.translationstudio.newui.translate.ChooseSourceTranslationDialog$3.onClick(ChooseSourceTranslationDialog.java:125)
	at android.view.View.performClick(View.java:4848)
	at android.view.View$PerformClick.run(View.java:20262)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

**Comment by neutrinog** [comment]
this has been fixed.
