### ISSUE TITLE
was trying to open it to use

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1487]
Notes
======
was trying to open it to use

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 128
UDID | ad6324947b6118d5
Android Release | 4.2.2
Android SDK | 17
Brand | rk31sdk
Device | rk31sdk
Stack trace
======
```java
android.view.InflateException: Binary XML file line #3: Error inflating class java.lang.reflect.Constructor
	at android.preference.GenericInflater.createItem(GenericInflater.java:397)
	at android.preference.GenericInflater.onCreateItem(GenericInflater.java:417)
	at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:428)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
	at android.preference.GenericInflater.inflate(GenericInflater.java:326)
	at android.preference.GenericInflater.inflate(GenericInflater.java:263)
	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:269)
	at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:482)
	at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:441)
	at com.door43.translationstudio.tasks.UpdateAppTask.performUpdates(UpdateAppTask.java:97)
	at com.door43.translationstudio.tasks.UpdateAppTask.start(UpdateAppTask.java:69)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.preference.GenericInflater.createItem(GenericInflater.java:383)
	... 14 more
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:202)
	at android.os.Handler.<init>(Handler.java:116)
	at android.widget.Editor$UserDictionaryListener.<init>(Editor.java:3836)
	at android.widget.Editor.<init>(Editor.java:192)
	at android.widget.TextView.createEditorIfNeeded(TextView.java:8475)
	at android.widget.TextView.<init>(TextView.java:1114)
	at android.widget.EditText.<init>(EditText.java:60)
	at android.widget.EditText.<init>(EditText.java:56)
	at android.preference.EditTextPreference.<init>(EditTextPreference.java:56)
	at android.preference.EditTextPreference.<init>(EditTextPreference.java:71)
	... 17 more

```
Log history
======
```java
5/4/16 11:09 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation hi_act_text_reg
5/4/16 11:09 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation hi_act_text_reg
     

```

**Comment by neutrinog** [comment]
this has already been fixed

**Comment by Arunm619** [comment]
How was this fixed?
