### ISSUE TITLE
I was uploading a ORA project, Nigeria to door43

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1495]
Notes
======
I was uploading a ORA project, Nigeria to door43

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 128
UDID | 7afb0cb6eaee9c
Android Release | 4.4.2
Android SDK | 19
Brand | samsung
Device | ja3g
Stack trace
======
```java
java.lang.NullPointerException
	at com.door43.translationstudio.tasks.LoginDoor43Task.start(LoginDoor43Task.java:85)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

```
Log history
======
```java
5/18/16 8:31 AM  W/com.door43.translationstudio.tasks.LoginDoor43Task: gogs api responded with 401: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/users/Pungs/tokens
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:186)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createToken(GogsAPI.java:399)
	at com.door43.translationstudio.tasks.LoginDoor43Task.start(LoginDoor43Task.java:74)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

5/18/16 7:20 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of commit command
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:317)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:969)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1005)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/sdcard/translationStudio/translations/ema-x-ora_mrk_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:235)
	... 2 more

5/17/16 9:31 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation ema-x-ora_mrk_text_reg
java.io.FileNotFoundException: /storage/sdcard/translationStudio/translations/ema-x-ora_mrk_text_reg/.git/index.lock: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:409)
	at java.io.FileInputStream.<init>(FileInputStream.java:78)
	at java.io.FileInputStream.<init>(FileInputStream.java:105)
	at com.door43.util.Zip.zipSubFolder(Zip.java:224)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:263)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:233)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:228)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:115)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
	at libcore.io.IoBridge.open(IoBridge.java:393)
	... 12 more

5/17/16 9:28 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation ema-x-ora_mrk_text_reg
5/17/16 12:30 PM  E/com.door43.translationstudio.service.BroadcastListenerService: Broadcast listener encountered an exception
java.net.SocketException: Socket closed
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:141)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
	at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161)
	at java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169)
	at java.net.DatagramSocket.receive(DatagramSocket.java:250)
	at java.nio.DatagramChannelImpl$DatagramSocketAdapter.receive(DatagramChannelImpl.java:548)
	at com.door43.translationstudio.network.BroadcastListenerRunnable.run(BroadcastListenerRunnable.java:64)
	at java.lang.Thread.run(Thread.java:841)

5/17/16 12:27 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation ema-x-ora_mrk_text_reg
5/17/16 12:27 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation ema-x-ora_mrk_text_reg
5/17/16 12:26 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation ema-x-ora_rom_text_reg
5/17/16 12:26 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation ema-x-ora_rom_text_reg
     

```

**Comment by neutrinog** [comment]
this has already been fixed.
