### ISSUE TITLE
App crashed when selecting source translation

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1500]
There were duplicates of ULB and UDB in the source translation selector.
Clicking on one would crash the app while the other would select the source translation as expected.

Environment
======
Environment Key | Value
:----: | :----:
version | 8.0
build | 129
UDID | f6b1fd4623e9d222
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Stack trace
======
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.door43.translationstudio.core.SourceTranslation.getId()' on a null object reference
	at com.door43.translationstudio.newui.translate.FirstTabFragment.onConfirmTabsDialog(FirstTabFragment.java:116)
	at com.door43.translationstudio.newui.translate.ChooseSourceTranslationDialog$3.onClick(ChooseSourceTranslationDialog.java:125)
	at android.view.View.performClick(View.java:4809)
	at android.view.View$PerformClick.run(View.java:20123)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

```
Log history
======
```java
5/19/16 1:21 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en_psa_text_reg
5/17/16 4:43 PM  W/com.door43.translationstudio.core.Downloader: Failed to fetch the catalog from https://api.unfoldingword.org/obs/txt/1/fr/CQ-fr.json
5/17/16 4:43 PM  E/com.door43.translationstudio.core.Downloader: Failed to download file
java.io.FileNotFoundException: https://api.unfoldingword.org/obs/txt/1/fr/CQ-fr.json
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at com.door43.translationstudio.core.Downloader.request(Downloader.java:44)
	at com.door43.translationstudio.core.Downloader.downloadCheckingQuestions(Downloader.java:269)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:293)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:244)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

5/17/16 4:43 PM  W/com.door43.translationstudio.core.Downloader: Failed to fetch the catalog from https://api.unfoldingword.org/obs/txt/1/fr/tN-fr.json
5/17/16 4:43 PM  E/com.door43.translationstudio.core.Downloader: Failed to download file
java.io.FileNotFoundException: https://api.unfoldingword.org/obs/txt/1/fr/tN-fr.json
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at com.door43.translationstudio.core.Downloader.request(Downloader.java:44)
	at com.door43.translationstudio.core.Downloader.downloadNotes(Downloader.java:248)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:285)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:244)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

5/17/16 4:43 PM  W/com.door43.translationstudio.core.Downloader: Failed to fetch the catalog from https://api.unfoldingword.org/obs/txt/1/fr/tw_cat-fr.json
5/17/16 4:43 PM  E/com.door43.translationstudio.core.Downloader: Failed to download file
java.io.FileNotFoundException: https://api.unfoldingword.org/obs/txt/1/fr/tw_cat-fr.json
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at com.door43.translationstudio.core.Downloader.request(Downloader.java:44)
	at com.door43.translationstudio.core.Downloader.downloadWordAssignments(Downloader.java:227)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:277)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:244)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

5/17/16 4:43 PM  W/com.door43.translationstudio.core.Downloader: Failed to fetch the catalog from https://api.unfoldingword.org/obs/txt/1/fr/kt-fr.json
5/17/16 4:43 PM  E/com.door43.translationstudio.core.Downloader: Failed to download file
java.io.FileNotFoundException: https://api.unfoldingword.org/obs/txt/1/fr/kt-fr.json
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at com.door43.translationstudio.core.Downloader.request(Downloader.java:44)
	at com.door43.translationstudio.core.Downloader.downloadWords(Downloader.java:206)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:269)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:244)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

5/17/16 12:39 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation en_psa_text_reg
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:263)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:233)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:228)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:115)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/17/16 10:38 AM  E/com.door43.translationstudio.newui.home.RestoreFromDoor43Dialog: Failed to open the online backup
5/17/16 10:38 AM  E/com.door43.translationstudio.tasks.CloneRepositoryTask: git@git.door43.org:joel/en_bible_tw.git: Auth fail
org.eclipse.jgit.api.errors.TransportException: git@git.door43.org:joel/en_bible_tw.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
	at com.door43.translationstudio.tasks.CloneRepositoryTask.start(CloneRepositoryTask.java:56)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.TransportException: git@git.door43.org:joel/en_bible_tw.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 7 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 14 more

5/17/16 9:19 AM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation aa_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:263)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:233)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:228)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:115)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/17/16 9:19 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

5/17/16 7:12 AM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation en_psa_text_reg
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:263)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:233)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:228)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:115)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/17/16 5:14 AM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation en_psa_text_reg
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:263)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:233)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:228)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:115)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/17/16 12:47 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en_psa_text_reg
     

```

**Comment by neutrinog** [comment]
this is an api issue. someone changed the id's of the `ulb` and `udb` resources in the api from `ulb` and `udb` to `ulb-en` and `udb-en`. A fixed has been made in the app to not crash anymore, but the api needs to be fixed to prevent problems with older versions of the app.

**Comment by cckozie** [comment]
@neutrinog Is there a way to test this in the current version of the app?

**Comment by neutrinog** [comment]
@cckozie the api has already been fixed so no. However, I tested it myself before it was fixed and the app will no longer crash.
