### ISSUE TITLE
logging in

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1510]
Notes
======
logging in

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 128
UDID | efdcf47520908f9d
Android Release | 4.4.2
Android SDK | 19
Brand | Allwinner
Device | astar-y3
Stack trace
======
```java
java.lang.NullPointerException
	at com.door43.translationstudio.tasks.LoginDoor43Task.start(LoginDoor43Task.java:85)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

```
Log history
======
```java
5/20/16 9:32 AM  W/com.door43.translationstudio.tasks.LoginDoor43Task: gogs api responded with 401: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/users/keriecks/tokens
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:186)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createToken(GogsAPI.java:399)
	at com.door43.translationstudio.tasks.LoginDoor43Task.start(LoginDoor43Task.java:74)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

5/20/16 9:32 AM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 2 inuw-psa-aaa
5/20/16 9:32 AM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 2 inuw-obs-aa
     

```

**Comment by neutrinog** [comment]
already fixed
