### ISSUE TITLE
putting the verses

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1574]
Notes
======
putting the verses

Environment
======
Environment Key | Value
:----: | :----:
version | 9.0
build | 138
UDID | 9c01f38519e8d28b
Android Release | 4.4.4
Android SDK | 19
Brand | samsung
Device | gtel3g
Stack trace
======
```java
java.lang.IndexOutOfBoundsException: getChars (0 ... 255) ends beyond length 0
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1016)
	at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:913)
	at android.text.TextUtils.getChars(TextUtils.java:82)
	at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:61)
	at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:905)
	at com.door43.translationstudio.newui.translate.ReviewModeAdapter$23$1.onDrag(ReviewModeAdapter.java:1420)
	at android.view.View.dispatchDragEvent(View.java:17624)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1333)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1175)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5244)
	at android.view.ViewRootImpl.access$900(ViewRootImpl.java:115)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3456)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5590)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)

```
Log history
======
```java
7/28/16 10:23 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation keu_mrk_text_reg
7/28/16 10:23 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation keu_mrk_text_reg
7/28/16 9:11 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation keu_mat_text_reg
7/28/16 9:11 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation keu_mat_text_reg
     

```

**Comment by PhotoNomad0** [comment]
Related to #1573, fixing there.
