### ISSUE TITLE
I receive an error anytime I try to create a ne...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1594]
Notes
======
I receive an error anytime I try to create a new door43 account from within the app, although I can do it online on the web at git.door43.org from my computer

Environment
======
Environment Key | Value
:----: | :----:
version | 9.0
build | 138
UDID | 22fee0d01254a33c
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Log history
======
```java
9/14/16 12:41 PM  W/com.door43.translationstudio.tasks.RegisterDoor43Task: The gogs admin token is missing
9/14/16 11:21 AM  E/com.door43.translationstudio.service.BroadcastListenerService: Broadcast listener encountered an exception
java.net.SocketException: Socket closed
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:161)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:593)
	at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:163)
	at java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:171)
	at java.net.DatagramSocket.receive(DatagramSocket.java:274)
	at java.nio.DatagramChannelImpl$DatagramSocketAdapter.receive(DatagramChannelImpl.java:597)
	at com.door43.translationstudio.network.BroadcastListenerRunnable.run(BroadcastListenerRunnable.java:64)
	at java.lang.Thread.run(Thread.java:818)

9/14/16 11:21 AM  E/com.door43.translationstudio.service.BroadcastListenerService: Broadcast listener encountered an exception
java.net.SocketException: Socket closed
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:161)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:593)
	at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:163)
	at java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:171)
	at java.net.DatagramSocket.receive(DatagramSocket.java:274)
	at java.nio.DatagramChannelImpl$DatagramSocketAdapter.receive(DatagramChannelImpl.java:597)
	at com.door43.translationstudio.network.BroadcastListenerRunnable.run(BroadcastListenerRunnable.java:64)
	at java.lang.Thread.run(Thread.java:818)

9/14/16 11:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmy-x-vc_obs_text_obs
9/14/16 11:20 AM  E/com.door43.translationstudio.newui.home.ImportFromDoor43Dialog: Failed to open the online backup
9/14/16 11:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmy-x-vg_obs_text_obs
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_rom_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_phm_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_tit_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_rev_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_php_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_obs_text_obs
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_mrk_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_mat_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_2jn_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_1pe_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_1jn_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_1co_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_jhn_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bha_jhn_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_act_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_luk_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_heb_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_eph_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_jas_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_1ti_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_gal_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_col_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_1th_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bha_luk_text_ulb
9/14/16 11:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_2co_text_ulb
9/14/16 11:18 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation rmr-x-bsa_jud_text_ulb
9/14/16 11:18 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation hr_obs_text_obs
9/14/16 11:18 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation hu_obs_text_obs
9/14/16 11:18 AM  W/com.door43.translationstudio.tasks.LoginDoor43Task: The full_name could not be updated gogs api responded with 403: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/admin/users/romastandarddemo
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.editUser(GogsAPI.java:213)
	at com.door43.translationstudio.tasks.LoginDoor43Task.start(LoginDoor43Task.java:89)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

     

```

**Comment by neutrinog** [comment]
this was just because the gogs token was not included during the build process. This has been fixed.

**Comment by cckozie** [comment]
Fails in build 143

**Comment by PhotoNomad0** [comment]
@cckozie - this is working in build 149.

**Comment by cckozie** [comment]
Broken in v11 - 153
![screenshot_2017-01-25-00-44-00](https://cloud.githubusercontent.com/assets/8171759/22257049/5db6aa7c-e222-11e6-885c-779a6ddf4a16.png)

**Comment by cckozie** [comment]
Works in travis build 1123
