### ISSUE TITLE
I'm the technician here in PR, the chrome noteb...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1719]
Notes
======
I'm the technician here in PR, the chrome notebook keeps crashing when trying to load Translation Studio.

Environment
======
Environment Key | Value
:----: | :----:
version | 9.0
build | 138
UDID | bb705b5477c70fbd
Android Release | 6.0.1
Android SDK | 23
Brand | google
Device | cyan_cheets
Stack trace
======
```java
org.eclipse.jgit.api.errors.JGitInternalException: Exception occurred during adding of AnyObjectId[8fe06f7c36f2c95104ed68d64fa92aec3d900ca7] as option to a Log command
	at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:340)
	at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:189)
	at com.door43.translationstudio.core.FileHistory.loadCommits(FileHistory.java:67)
	at com.door43.translationstudio.newui.translate.ReviewModeAdapter$10.run(ReviewModeAdapter.java:657)
	at com.door43.util.tasks.ThreadableUI$1.run(ThreadableUI.java:27)
Caused by: java.io.EOFException: Short read of block.
	at org.eclipse.jgit.util.IO.readFully(IO.java:248)
	at org.eclipse.jgit.internal.storage.file.UnpackedObject.open(UnpackedObject.java:108)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openLooseObject(ObjectDirectory.java:441)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openLooseFromSelfOrAlternate(ObjectDirectory.java:399)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:381)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:145)
	at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:884)
	at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:145)
	at org.eclipse.jgit.revwalk.RevWalk.markStart(RevWalk.java:280)
	at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:330)
	... 4 more

```
Log history
======
```java
12/6/16 5:32 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:971)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:934)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/translationStudio/translations/es-419_gen_text_reg/19/10.txt: open failed: EIO (I/O error)
	at libcore.io.IoBridge.open(IoBridge.java:452)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at org.eclipse.jgit.treewalk.FileTreeIterator$FileEntry.openInputStream(FileTreeIterator.java:210)
	at org.eclipse.jgit.treewalk.WorkingTreeIterator.getEntryContentLength(WorkingTreeIterator.java:533)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:184)
	... 6 more
Caused by: android.system.ErrnoException: open failed: EIO (I/O error)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:438)
	... 10 more

12/6/16 5:19 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:971)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:934)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/translationStudio/translations/es-419_gen_text_reg/19/10.txt: open failed: EIO (I/O error)
	at libcore.io.IoBridge.open(IoBridge.java:452)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at org.eclipse.jgit.treewalk.FileTreeIterator$FileEntry.openInputStream(FileTreeIterator.java:210)
	at org.eclipse.jgit.treewalk.WorkingTreeIterator.getEntryContentLength(WorkingTreeIterator.java:533)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:184)
	... 6 more
Caused by: android.system.ErrnoException: open failed: EIO (I/O error)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:438)
	... 10 more

12/6/16 5:19 PM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation es-419_gen_text_reg
12/6/16 5:19 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation es-419_rom_text_ulb
12/6/16 5:19 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation es-419_rom_text_udb
12/6/16 5:19 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation es-419_1co_text_ulb
     

```

**Comment by PhotoNomad0** [comment]
@neutrinog @klappy - I'm not sure about this.  It looks like they are trying to run the android app on a Chromebook?  Not sure how to proceed without a Chrome Notebook.  Not sure who the technician is in PR.

**Comment by neutrinog** [comment]
We do not officially support the chrome book. However Google is extending
android app support to Chromebooks in the near future (next year??) at
which point the app should run on it.
