### ISSUE TITLE
photonomad- Downloading

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1726]
Notes
======
photonomad- Downloading

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 149
UDID | 213f93abcdcb049
Android Release | 4.4.2
Android SDK | 19
Brand | Allwinner
Device | astar-y3
Stack trace
======
```java
java.lang.OutOfMemoryError
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorOutputStream$Data.<init>(BZip2CompressorOutputStream.java:1329)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorOutputStream.init(BZip2CompressorOutputStream.java:527)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorOutputStream.<init>(BZip2CompressorOutputStream.java:391)
	at org.apache.commons.compress.compressors.bzip2.BZip2CompressorOutputStream.<init>(BZip2CompressorOutputStream.java:357)
	at org.unfoldingword.resourcecontainer.ResourceContainer.close(ResourceContainer.java:259)
	at org.unfoldingword.door43client.API.convertLegacyResource(API.java:500)
	at org.unfoldingword.door43client.API.downloadResourceContainer(API.java:363)
	at org.unfoldingword.door43client.Door43Client.download(Door43Client.java:122)
	at com.door43.translationstudio.tasks.DownloadResourceContainersTask.start(DownloadResourceContainersTask.java:55)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

```

**Comment by PhotoNomad0** [comment]
we have issues with older phones and upgrading apps.
