### ISSUE TITLE
selecting the source text for a project

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1812]
Notes
======
selecting the source text for a project

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 153
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Stack trace
======
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setBackgroundResource(int)' on a null object reference
	at com.door43.translationstudio.ui.translate.ChooseSourceTranslationAdapter.getView(ChooseSourceTranslationAdapter.java:358)
	at android.widget.AbsListView.obtainView(AbsListView.java:2347)
	at android.widget.ListView.makeAndAddView(ListView.java:1864)
	at android.widget.ListView.fillDown(ListView.java:698)
	at android.widget.ListView.fillSpecific(ListView.java:1356)
	at android.widget.ListView.layoutChildren(ListView.java:1651)
	at android.widget.AbsListView.onLayout(AbsListView.java:2151)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```
Log history
======
```java
2/9/17 8:56 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:56 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:56 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:56 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:56 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:56 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:56 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_jhn_text_reg
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation kcg_mrk_text_reg
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo2_obs_text_obs
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_mrk_text_reg
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_rut_text_reg
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo2_tit_text_reg
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_mat_text_reg
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_tit_text_reg
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en_obs_text_obs
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en_3jn_text_reg
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_3jn_text_reg
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en_2jn_text_reg
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_jud_text_reg
2/9/17 8:56 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_phm_text_reg
2/9/17 8:56 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:56 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aaa_php_text_ulb
2/9/17 8:55 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:55 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:54 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:54 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:54 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:54 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_jhn_text_reg
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation kcg_mrk_text_reg
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo2_obs_text_obs
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_mrk_text_reg
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_rut_text_reg
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo2_tit_text_reg
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_mat_text_reg
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_tit_text_reg
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en_obs_text_obs
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en_3jn_text_reg
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_3jn_text_reg
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en_2jn_text_reg
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_jud_text_reg
2/9/17 8:54 AM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_phm_text_reg
2/9/17 8:54 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
2/9/17 8:53 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aaa_php_text_ulb
2/9/17 8:51 AM  E/com.door43.translationstudio.services.BackupService: runBackup: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1025)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:988)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:119)
	at com.door43.translationstudio.services.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jhn_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

2/9/17 8:51 AM  E/com.door43.translationstudio.services.BackupService: runBackup: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1025)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:988)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:119)
	at com.door43.translationstudio.services.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/kcg_mrk_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

     

```

**Comment by cckozie** [comment]
This is the project I was using. It was created a couple days ago, but I had not yet selected a source language. This crash occurred 3 times, and was one of the first activities I did after installing the latest build. After tS recovered the third time I exited the app using the back triangle, and when I opened it again, I was able to choose the source without the app crashing. Could this be related to the continuing problem after an install to where it displays the Welcome to tS message even tho the app is running in the background?
[en-x-demo2_gen_text_reg.zip](https://github.com/unfoldingWord-dev/ts-android/files/764033/en-x-demo2_gen_text_reg.zip)
