### ISSUE TITLE
after upgrading to build 1139 I have to again c...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1815]
Notes
======
after upgrading to build 1139 I have to again choose a source language when opening existing projects.

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 153
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Log history
======
```java
2/9/17 3:14 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_num_text_reg
2/9/17 3:14 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_num_text_reg
2/9/17 3:02 PM  E/ReviewModeAdapter: renderTargetCard(): Position 177: Add task failed, verify task null,  ID: 471
2/9/17 3:02 PM  E/ReviewModeAdapter: renderTargetCard(): Position 587: Add task failed, verify task null,  ID: 445
2/9/17 2:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
2/9/17 2:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
2/9/17 2:49 PM  E/com.door43.translationstudio.services.BackupService: runBackup: Failed to backup the target translation en-x-demo1_php_text_reg
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:333)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:497)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:128)
	at com.door43.translationstudio.services.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/9/17 2:34 PM  E/com.door43.translationstudio.services.BackupService: runBackup: Failed to backup the target translation en-x-demo1_php_text_reg
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:333)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:497)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:128)
	at com.door43.translationstudio.services.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/9/17 2:33 PM  E/com.door43.translationstudio.services.BackupService: runBackup: Failed to backup the target translation en-x-demo1_php_text_reg
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:333)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:497)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:128)
	at com.door43.translationstudio.services.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/9/17 1:31 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/9/17 1:31 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/9/17 1:31 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/9/17 1:31 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/9/17 1:31 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/9/17 1:31 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/9/17 1:31 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
     

```

**Comment by neutrinog** [comment]
@cckozie This is probably because we changed to using the resource containers so all the old bookmark id's all get lost. I'm not certain this is worth fixing because it'll only happen once and there are lots of other things to fix.

**Comment by klappy** [comment]
I think it's worth putting in before 11 is released even if it delays it a little. There may be other priorities to fix first, we can queue it up but do our best to fit this in.

**Comment by neutrinog** [comment]
this is now fixed. Also, fixed some bugs in loading the last translation mode.
