### ISSUE TITLE
blank screen after selecting a second source la...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1841]
Notes
======
blank screen after selecting a second source language

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 153
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Log history
======
```java
2/15/17 10:05 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
2/15/17 10:04 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1079)

2/15/17 10:04 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 10:04 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 10:04 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
2/15/17 10:04 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
2/15/17 10:03 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1079)

2/15/17 10:03 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 10:03 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 10:03 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
2/15/17 10:03 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
2/15/17 10:03 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
2/15/17 10:02 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1079)

2/15/17 10:02 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 10:02 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 10:02 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
2/15/17 10:02 AM  I/DownloadSourcesAdapter: Found 840 sources
2/15/17 10:02 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
2/15/17 10:01 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1079)

2/15/17 10:01 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 10:01 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 10:01 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
2/15/17 10:01 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
2/15/17 10:00 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1079)

2/15/17 10:00 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 10:00 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 10:00 AM  I/HomeActivity: total memory on the system: 1894551552
2/15/17 10:00 AM  I/HomeActivity: low memory threshold on the system: 150994944
2/15/17 10:00 AM  I/HomeActivity: low memory state on the system: false
2/15/17 10:00 AM  I/HomeActivity: available memory on the system: 612630528
2/15/17 10:00 AM  I/HomeActivity: application memory limit: 192
2/15/17 10:00 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
2/15/17 9:59 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
2/15/17 9:58 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1079)

2/15/17 9:58 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 9:58 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 9:58 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
2/15/17 9:58 AM  I/HomeActivity: total memory on the system: 1894551552
2/15/17 9:58 AM  I/HomeActivity: low memory threshold on the system: 150994944
2/15/17 9:58 AM  I/HomeActivity: low memory state on the system: false
2/15/17 9:58 AM  I/HomeActivity: available memory on the system: 618094592
2/15/17 9:58 AM  I/HomeActivity: application memory limit: 192
2/15/17 9:58 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_1th_text_reg
2/15/17 9:58 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_1th_text_reg
2/15/17 9:58 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
2/15/17 9:57 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1079)

2/15/17 9:57 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 9:57 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 9:57 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
2/15/17 9:57 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
2/15/17 9:56 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1079)

2/15/17 9:56 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 9:56 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 9:56 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
2/15/17 9:56 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
2/15/17 9:55 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1079)

2/15/17 9:55 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 9:55 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/15/17 9:55 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
     

```

**Comment by cckozie** [comment]
I think I caused this by corrupting a file.
