### ISSUE TITLE
Failed to backup the translation of Titus into ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1849]
Notes
======
Failed to backup the translation of Titus into Loubala.
targetTranslation: qaa-x-1560c6_tit_text_reg
--------

Follow on to issus 1848

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 153
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Log history
======
```java
2/16/17 10:41 AM  W/com.door43.translationstudio.tasks.CreateRepositoryTask: Failed to create repository qaa-x-1560c6_tit_text_reg. Gogs responded with 500: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/user/repos
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createRepo(GogsAPI.java:336)
	at com.door43.translationstudio.tasks.CreateRepositoryTask.start(CreateRepositoryTask.java:37)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

2/16/17 10:41 AM  I/com.door43.translationstudio.ui.dialogs.BackupDialog: The repository qaa-x-1560c6_tit_text_reg could not be found
2/16/17 10:41 AM  E/com.door43.translationstudio.tasks.PullTargetTranslationTask: Invalid remote: origin
org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:136)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:261)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.pull(PullTargetTranslationTask.java:148)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.start(PullTargetTranslationTask.java:82)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: git@git.door43.org:qa98/qaa-x-1560c6_tit_text_reg.git: Gogs: Repository does not exist or you do not have access
Repository does not exist: qa98/qaa-x-1560c6_tit_text_reg

	at org.eclipse.jgit.transport.TransportGitSsh.cleanNotFound(TransportGitSsh.java:208)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:288)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 7 more

2/16/17 10:41 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
     

```

**Comment by cckozie** [comment]
See #1848
