### ISSUE TITLE
trying to export project file

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1855]
Notes
======
trying to export project file

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 155
UDID | a4b66484d349dee1
Android Release | 5.0.2
Android SDK | 21
Brand | lge
Device | e9wifi
Log history
======
```java
2/17/17 11:26 AM  E/com.door43.translationstudio.ui.dialogs.BackupDialog: Failed to export the target translation en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.core.TargetTranslation.getGitHead(TargetTranslation.java:1272)
	at com.door43.translationstudio.core.TargetTranslation.getCommitHash(TargetTranslation.java:1253)
	at com.door43.translationstudio.core.Translator.buildArchiveManifest(Translator.java:285)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:326)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.ui.dialogs.BackupDialog.doSdCardBackup(BackupDialog.java:498)
	at com.door43.translationstudio.ui.dialogs.BackupDialog.access$700(BackupDialog.java:65)
	at com.door43.translationstudio.ui.dialogs.BackupDialog$12.onClick(BackupDialog.java:460)
	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

2/17/17 11:26 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:426)
	at java.net.InetAddress.getLocalHost(InetAddress.java:399)
	at org.eclipse.jgit.util.SystemReader$Default.getHostname(SystemReader.java:118)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:222)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:523)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:198)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.ui.dialogs.BackupDialog.doSdCardBackup(BackupDialog.java:498)
	at com.door43.translationstudio.ui.dialogs.BackupDialog.access$700(BackupDialog.java:65)
	at com.door43.translationstudio.ui.dialogs.BackupDialog$12.onClick(BackupDialog.java:460)
	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

2/17/17 11:25 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
2/17/17 11:24 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
     

```

**Comment by cckozie** [comment]
I chose the export project file option and was presented with the Enable SD Card Access screen. I chose CONFIRM, then on the next screen I used the Android back triangle to cancel the process. I then again chose the export project file option and chose SKIP on the Enable SD Card screen. The export failed.

**Comment by neutrinog** [comment]
@cckozie congrats! I've never known anyone to find more ways to corrupt a git repository than you!
Pushed a fix.

**Comment by cckozie** [comment]
@neutrinog Thanks! Just trying to do my job...break stuff.
