### ISSUE TITLE
Project disappeared on home screen after upload...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1875]
Notes
======
Project disappeared on home screen after uploading to for 43

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 155
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Log history
======
```java
2/20/17 4:40 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen-x-demo1_php_text_reg
2/20/17 4:40 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen-x-demo1_php_text_reg
2/20/17 4:39 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen-x-demo1_php_text_reg
2/20/17 4:38 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen-x-demo1_php_text_reg
2/20/17 4:38 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen-x-demo1_php_text_reg
2/20/17 4:36 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen-x-demo1_php_text_reg
2/20/17 4:36 PM  E/com.door43.translationstudio.tasks.PullTargetTranslationTask: git@git.door43.org:qa99/en-x-demo1_php_text_reg.git: Auth fail
org.eclipse.jgit.api.errors.TransportException: git@git.door43.org:qa99/en-x-demo1_php_text_reg.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:261)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.pull(PullTargetTranslationTask.java:148)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.start(PullTargetTranslationTask.java:82)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.TransportException: git@git.door43.org:qa99/en-x-demo1_php_text_reg.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 7 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 14 more

2/20/17 4:34 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:34 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:34 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:34 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:34 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:34 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:34 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation translation
2/20/17 3:00 PM  W/com.door43.translationstudio.tasks.CreateRepositoryTask: Failed to create repository qaa-x-1560c6_tit_text_reg. Gogs responded with 500: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/user/repos
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createRepo(GogsAPI.java:336)
	at com.door43.translationstudio.tasks.CreateRepositoryTask.start(CreateRepositoryTask.java:37)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

2/20/17 3:00 PM  E/com.door43.translationstudio.tasks.PullTargetTranslationTask: Invalid remote: origin
org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:136)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:261)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.pull(PullTargetTranslationTask.java:148)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.start(PullTargetTranslationTask.java:82)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: git@git.door43.org:qa1/qaa-x-1560c6_tit_text_reg.git: Gogs: Repository does not exist or you do not have access
Repository does not exist: qa1/qaa-x-1560c6_tit_text_reg

	at org.eclipse.jgit.transport.TransportGitSsh.cleanNotFound(TransportGitSsh.java:208)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:288)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 7 more

2/20/17 3:00 PM  E/com.door43.translationstudio.tasks.PullTargetTranslationTask: git@git.door43.org:qa1/qaa-x-1560c6_tit_text_reg.git: Auth fail
org.eclipse.jgit.api.errors.TransportException: git@git.door43.org:qa1/qaa-x-1560c6_tit_text_reg.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:261)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.pull(PullTargetTranslationTask.java:148)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.start(PullTargetTranslationTask.java:82)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.TransportException: git@git.door43.org:qa1/qaa-x-1560c6_tit_text_reg.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 7 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 14 more

2/20/17 2:57 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation qaa-x-1560c6_tit_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.ui.home.TargetTranslationAdapter: Could not find a source translation for en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
2/20/17 2:53 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
     

```

**Comment by cckozie** [comment]
I was working on issue #1802. Following is the sequence of events:
I exited tS.
I downloaded the project zip file from 1802 and uncompressed the file.
I moved the uncompressed project into the translations folder.
I started tS and opened the download project.
I uploaded the project to door43.
When the upload succeeded I clicked on the view project link which opened the browser to the project.
I switched back to tS and clicked the Dismiss link on the upload dialog.
When the home screen was displayed, the uploaded project was no longer showing. The other two projects were displayed. The missing project is still in the translations folder.
I closed and reopened the app and now the project is again showing on the home screen.
