### ISSUE TITLE
scrolling through a project using the scroll bar

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1877]
Notes
======
scrolling through a project using the scroll bar

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 155
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Stack trace
======
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.unfoldingword.resourcecontainer.ResourceContainer.readChunk(java.lang.String, java.lang.String)' on a null object reference
	at com.door43.translationstudio.ui.translate.ReviewModeAdapter$31.start(ReviewModeAdapter.java:1843)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```
Log history
======
```java
2/21/17 9:23 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
2/21/17 9:22 AM  I/com.door43.translationstudio.services.BackupService: Backups running every 1 minute/s
2/21/17 9:22 AM  I/com.door43.translationstudio.services.BackupService: Backups running every 1 minute/s
2/21/17 9:22 AM  I/com.door43.translationstudio.services.BackupService: starting backup service
2/21/17 9:22 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
2/21/17 9:22 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1092)

2/21/17 9:22 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1092)

2/21/17 9:21 AM  E/ReviewModeAdapter: renderTargetCard(): Position 506: Add task failed, verify task null,  ID: 375
2/21/17 9:20 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1092)

2/21/17 9:20 AM  I/ViewModeFragment: doScrollToPosition: position=3, offset=0
2/21/17 9:19 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1092)

2/21/17 9:19 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/21/17 9:19 AM  E/com.door43.translationstudio.services.BackupService: Could not commit changes to en-x-demo1_num_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1059)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/21/17 9:19 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
2/21/17 9:18 AM  I/ViewModeFragment: doScrollToPosition: position=3, offset=0
2/21/17 9:17 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1092)

2/21/17 9:17 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1092)

2/21/17 9:17 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/21/17 9:17 AM  E/com.door43.translationstudio.services.BackupService: Could not commit changes to en-x-demo1_num_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1059)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:88)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/21/17 9:16 AM  E/ReviewModeAdapter: renderTargetCard(): Position 2: Add task failed, verify task null,  ID: 95
2/20/17 5:07 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1092)

2/20/17 5:07 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1092)

2/20/17 5:07 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$2.run(BackupService.java:233)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)

2/20/17 5:07 PM  E/com.door43.translationstudio.services.BackupService: Could not commit changes to en-x-demo1_num_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1059)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$2.run(BackupService.java:233)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)

2/20/17 5:06 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1092)

2/20/17 5:05 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1053)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1018)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.tasks.UpdateAppTask.updateTargetTranslations(UpdateAppTask.java:144)
	at com.door43.translationstudio.tasks.UpdateAppTask.start(UpdateAppTask.java:78)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

2/20/17 1:03 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1079)

2/20/17 1:03 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:324)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:303)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:491)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:161)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$2.run(BackupService.java:233)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)

2/20/17 1:03 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:153)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:36)
	at com.door43.translationstudio.services.BackupService$2.run(BackupService.java:233)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)

2/20/17 1:02 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_psa_text_reg
2/20/17 1:02 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_psa_text_reg
2/20/17 1:01 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:103)
	at com.door43.translationstudio.git.Repo.forceCall(Repo.java:194)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1043)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:990)
	at com.door43.translationstudio.tasks.UpdateAppTask.updateTargetTranslations(UpdateAppTask.java:144)
	at com.door43.translationstudio.tasks.UpdateAppTask.start(UpdateAppTask.java:78)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

     

```

**Comment by cckozie** [comment]
Haven't seen this is the latest builds.
