### ISSUE TITLE
attempting to export to SD csrd

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1880]
Notes
======
attempting to export to SD csrd

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 155
UDID | a4b66484d349dee1
Android Release | 5.0.2
Android SDK | 21
Brand | lge
Device | e9wifi
Log history
======
```java
2/21/17 4:09 PM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10134 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:3970)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1678)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:226)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:212)
	at com.door43.util.SdUtils.persistSdCardWriteAccess(SdUtils.java:182)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$8.run(DeveloperToolsActivity.java:164)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$4.onItemClick(DeveloperToolsActivity.java:118)
	at android.widget.AdapterView.performItemClick(AdapterView.java:300)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1186)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3099)
	at android.widget.AbsListView$3.run(AbsListView.java:4046)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

2/20/17 2:34 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
2/20/17 2:34 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
     

```

**Comment by cckozie** [comment]
Haven't seen this issue in the latest builds.
