### ISSUE TITLE
I was in my numbers project and used the Androi...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1882]
Notes
======
I was in my numbers project and used the Android square icon to open es file explorer to view the backup folder. When I went back to tS, instead of taking me back to the numbers project I was present the screen to click on the folder icon to select a source language for John.

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 156
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Log history
======
```java
2/21/17 4:49 PM  W/com.door43.translationstudio.services.BackupService: Could not commit changes to en-x-demo1_num_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1058)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:157)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:40)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:92)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/21/17 4:49 PM  W/com.door43.translationstudio.services.BackupService: Could not commit changes to en-x-demo1_php_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1058)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:157)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:40)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:92)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

2/21/17 4:48 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes for en-x-demo1_num_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1052)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1017)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1091)

2/21/17 4:46 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes for en-x-demo1_num_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1052)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1017)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1091)

2/21/17 4:44 PM  E/FirstTabFragment: Error getting resource container for 'en-x-demo1_num_text_reg'
java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.unfoldingword.resourcecontainer.Project.languageSlug' on a null object reference
	at com.door43.translationstudio.ui.translate.FirstTabFragment.onCreateView(FirstTabFragment.java:60)
	at android.app.Fragment.performCreateView(Fragment.java:2053)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.BackStackRecord.run(BackStackRecord.java:834)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
	at android.app.Activity.performStart(Activity.java:6005)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

2/21/17 4:43 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes for en-x-demo1_num_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1052)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1017)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1091)

2/21/17 4:41 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes for en-x-demo1_num_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1052)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1017)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1091)

2/21/17 4:39 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes for en-x-demo1_num_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1052)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1017)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1091)

2/21/17 4:37 PM  W/com.door43.translationstudio.services.BackupService: Could not commit changes to en-x-demo1_num_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1058)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:157)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:40)
	at com.door43.translationstudio.services.BackupService$2.run(BackupService.java:262)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)

2/21/17 4:37 PM  W/com.door43.translationstudio.services.BackupService: Could not commit changes to en-x-demo1_php_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1058)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:157)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:40)
	at com.door43.translationstudio.services.BackupService$2.run(BackupService.java:262)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)

2/21/17 4:36 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes for en-x-demo1_num_text_reg
org.eclipse.jgit.api.errors.ConcurrentRefUpdateException: Could not lock HEAD. RefUpdate return code was: LOCK_FAILURE
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:300)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1052)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1017)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:989)
	at com.door43.translationstudio.tasks.UpdateAppTask.updateTargetTranslations(UpdateAppTask.java:144)
	at com.door43.translationstudio.tasks.UpdateAppTask.start(UpdateAppTask.java:78)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

     

```

**Comment by cckozie** [comment]
![screenshot_2017-02-21-16-49-56](https://cloud.githubusercontent.com/assets/8171759/23189470/a8ae9868-f858-11e6-9292-79b59125b387.png)
![screenshot_2017-02-21-16-49-32](https://cloud.githubusercontent.com/assets/8171759/23189487/b2c40ffe-f858-11e6-90a4-5b6e7e26459a.png)
![screenshot_2017-02-21-16-49-56](https://cloud.githubusercontent.com/assets/8171759/23189498/ba3e8570-f858-11e6-8ee3-ebaa45366099.png)
