### ISSUE TITLE
doing an import from door43 of with previous pr...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1883]
Notes
======
doing an import from door43 of with previous project existing. I took the overwrite option and the app crashed.

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 156
UDID | a4b66484d349dee1
Android Release | 5.0.2
Android SDK | 21
Brand | lge
Device | e9wifi
Stack trace
======
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.door43.translationstudio.ui.home.HomeActivity.notifyDatasetChanged()' on a null object reference
	at com.door43.translationstudio.ui.home.ImportFromDoor43Dialog.onFinished(ImportFromDoor43Dialog.java:269)
	at org.unfoldingword.tools.taskmanager.SimpleTaskWatcher$1.run(SimpleTaskWatcher.java:158)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

```
Log history
======
```java
2/22/17 11:16 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_php_text_reg
2/22/17 11:15 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_php_text_reg
2/22/17 11:13 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_phm_text_reg
2/22/17 11:12 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_php_text_reg
2/22/17 11:11 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_php_text_reg
2/22/17 11:10 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_php_text_reg
2/22/17 11:05 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
2/22/17 11:05 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
     

```

**Comment by cckozie** [comment]
Works in travis build 1344
