### ISSUE TITLE
related to #1931

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1934]
Notes
======
related to #1931

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 156
UDID | 6b8537242b5c9d0d
Android Release | 6.0
Android SDK | 23
Brand | lge
Device | p1
Log history
======
```java
3/2/17 5:15 PM  E/com.door43.translationstudio.core.ExportUsfm: Failed to export the target translation en-x-demo1_act_text_reg
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.close()' on a null object reference
	at com.door43.translationstudio.core.ExportUsfm.exportAsUSFM(ExportUsfm.java:155)
	at com.door43.translationstudio.core.ExportUsfm.saveToUSFM(ExportUsfm.java:51)
	at com.door43.translationstudio.tasks.ExportToUsfmTask.start(ExportToUsfmTask.java:38)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

2/20/17 10:57 AM  E/com.door43.translationstudio.newui.home.ImportFromDoor43Dialog: Failed to open the online backup
2/20/17 10:57 AM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 7 inchrisjarka-nl_obs_text_obs1487606247808
2/20/17 10:37 AM  E/com.door43.translationstudio.newui.home.RestoreFromDoor43Dialog: Failed to open the online backup
2/20/17 10:37 AM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 7 inchrisjarka-nl_obs_text_obs1487605009295
2/20/17 10:36 AM  E/com.door43.translationstudio.tasks.CloneRepositoryTask: git@git.door43.org:chrisjarka/nl_obs_text_obs.git: Auth fail
org.eclipse.jgit.api.errors.TransportException: git@git.door43.org:chrisjarka/nl_obs_text_obs.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
	at com.door43.translationstudio.tasks.CloneRepositoryTask.start(CloneRepositoryTask.java:56)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.TransportException: git@git.door43.org:chrisjarka/nl_obs_text_obs.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 7 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 14 more

2/20/17 10:36 AM  E/com.door43.translationstudio.newui.home.ImportFromDoor43Dialog: Failed to open the online backup
2/20/17 10:36 AM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 7 inchrisjarka-nl_obs_text_obs1487604978366
11/17/16 4:33 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:971)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:934)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_gen_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

11/17/16 4:03 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:203)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:982)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:934)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_gen_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 7 more

10/11/16 4:54 PM  W/com.door43.translationstudio.core.Indexer: Failed to parse a question for act-en-udb
org.json.JSONException: No value for id
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.door43.translationstudio.core.Indexer.indexQuestions(Indexer.java:685)
	at com.door43.translationstudio.core.Downloader.downloadCheckingQuestions(Downloader.java:271)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:302)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:253)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

10/11/16 4:54 PM  W/com.door43.translationstudio.core.Indexer: Failed to parse a translation note for act-en-udb
org.json.JSONException: No value for id
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.door43.translationstudio.core.Indexer.indexTranslationNotes(Indexer.java:480)
	at com.door43.translationstudio.core.Downloader.downloadNotes(Downloader.java:250)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:294)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:253)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

10/11/16 4:54 PM  W/com.door43.translationstudio.core.Indexer: Failed to parse a translation word for act-en-udb
org.json.JSONException: No value for id
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.door43.translationstudio.core.TranslationWord.generate(TranslationWord.java:56)
	at com.door43.translationstudio.core.Indexer.indexTranslationWords(Indexer.java:589)
	at com.door43.translationstudio.core.Downloader.downloadWords(Downloader.java:208)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:278)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:253)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

10/11/16 4:54 PM  W/com.door43.translationstudio.core.Indexer: Failed to parse a question for act-en-ulb
org.json.JSONException: No value for id
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.door43.translationstudio.core.Indexer.indexQuestions(Indexer.java:685)
	at com.door43.translationstudio.core.Downloader.downloadCheckingQuestions(Downloader.java:271)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:302)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:253)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

10/11/16 4:54 PM  W/com.door43.translationstudio.core.Indexer: Failed to parse a translation note for act-en-ulb
org.json.JSONException: No value for id
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.door43.translationstudio.core.Indexer.indexTranslationNotes(Indexer.java:480)
	at com.door43.translationstudio.core.Downloader.downloadNotes(Downloader.java:250)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:294)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:253)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

10/11/16 4:54 PM  W/com.door43.translationstudio.core.Indexer: Failed to parse a translation word for act-en-ulb
org.json.JSONException: No value for id
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.door43.translationstudio.core.TranslationWord.generate(TranslationWord.java:56)
	at com.door43.translationstudio.core.Indexer.indexTranslationWords(Indexer.java:589)
	at com.door43.translationstudio.core.Downloader.downloadWords(Downloader.java:208)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:278)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:253)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

10/11/16 4:45 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_act_text_reg
10/11/16 4:45 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_act_text_reg
10/11/16 4:09 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_mat_text_reg
10/11/16 4:09 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_mat_text_reg
10/11/16 4:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_gen_text_reg
10/11/16 4:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_gen_text_reg
10/11/16 4:07 PM  W/com.door43.translationstudio.core.Indexer: Failed to parse a question for gen-en-udb
org.json.JSONException: No value for id
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.door43.translationstudio.core.Indexer.indexQuestions(Indexer.java:685)
	at com.door43.translationstudio.core.Downloader.downloadCheckingQuestions(Downloader.java:271)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:302)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:253)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

10/11/16 4:07 PM  W/com.door43.translationstudio.core.Indexer: Failed to parse a translation note for gen-en-udb
org.json.JSONException: No value for id
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.door43.translationstudio.core.Indexer.indexTranslationNotes(Indexer.java:480)
	at com.door43.translationstudio.core.Downloader.downloadNotes(Downloader.java:250)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:294)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:253)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

10/11/16 4:07 PM  W/com.door43.translationstudio.core.Indexer: Failed to parse a translation word for gen-en-udb
org.json.JSONException: No value for id
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.door43.translationstudio.core.TranslationWord.generate(TranslationWord.java:56)
	at com.door43.translationstudio.core.Indexer.indexTranslationWords(Indexer.java:589)
	at com.door43.translationstudio.core.Downloader.downloadWords(Downloader.java:208)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:278)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:253)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

10/11/16 4:07 PM  W/com.door43.translationstudio.core.Indexer: Failed to parse a question for gen-en-ulb
org.json.JSONException: No value for id
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.door43.translationstudio.core.Indexer.indexQuestions(Indexer.java:685)
	at com.door43.translationstudio.core.Downloader.downloadCheckingQuestions(Downloader.java:271)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:302)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:253)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

10/11/16 4:07 PM  W/com.door43.translationstudio.core.Indexer: Failed to parse a translation note for gen-en-ulb
org.json.JSONException: No value for id
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.door43.translationstudio.core.Indexer.indexTranslationNotes(Indexer.java:480)
	at com.door43.translationstudio.core.Downloader.downloadNotes(Downloader.java:250)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:294)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:253)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

10/11/16 4:07 PM  W/com.door43.translationstudio.core.Indexer: Failed to parse a translation word for gen-en-ulb
org.json.JSONException: No value for id
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.door43.translationstudio.core.TranslationWord.generate(TranslationWord.java:56)
	at com.door43.translationstudio.core.Indexer.indexTranslationWords(Indexer.java:589)
	at com.door43.translationstudio.core.Downloader.downloadWords(Downloader.java:208)
	at com.door43.translationstudio.core.Library.startSourceTranslationDownload(Library.java:278)
	at com.door43.translationstudio.core.Library.downloadSourceTranslation(Library.java:253)
	at com.door43.translationstudio.tasks.DownloadSourceLanguageTask.start(DownloadSourceLanguageTask.java:45)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

     

```

**Comment by ChrisJarka** [comment]
This is the same issue as https://github.com/unfoldingWord-dev/ts-android/issues/1931 only on my phone with an external SD card.
