### ISSUE TITLE
please change spelling of timne to themne

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1962]
Notes
======
please change spelling of timne to themne

Environment
======
Environment Key | Value
:----: | :----:
version | 9.0
build | 138
UDID | 3528f2e289356096
Android Release | 5.0.1
Android SDK | 21
Brand | lge
Device | g3
Log history
======
```java
2/9/17 8:31 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation tem_obs_text_obs
2/9/17 8:31 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation tem_obs_text_obs
1/25/17 5:00 AM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation tem_gen_text_reg
java.lang.NullPointerException
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:263)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:233)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:229)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:115)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

     

```

**Comment by PhotoNomad0** [comment]
@neutrinog - this looks like a request to change spelling of a dialect.  Do we forward this to the web team?
