### ISSUE TITLE
added second source, scrolled, switched to othe...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1965]
Notes
======
added second source, scrolled, switched to other source, scrolled, switched back to original source, crash

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 158
UDID | a4b66484d349dee1
Android Release | 5.0.2
Android SDK | 21
Brand | lge
Device | e9wifi
Stack trace
======
```java
java.lang.IndexOutOfBoundsException: Invalid index 383, size is 383
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.door43.translationstudio.ui.translate.ReviewModeAdapter.runTaskGarbageCollection(ReviewModeAdapter.java:371)
	at com.door43.translationstudio.ui.translate.ReviewModeAdapter.onVisiblePositionsChanged(ReviewModeAdapter.java:360)
	at com.door43.translationstudio.ui.translate.ViewModeAdapter.onBindViewHolder(ViewModeAdapter.java:68)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6310)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6343)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5289)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5552)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3266)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2102)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

```
Log history
======
```java
3/9/17 9:49 AM  E/com.door43.translationstudio.services.BackupService: Could not backup en-x-demo2_php_text_reg
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:606)
	at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:790)
	at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
	at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:825)
	at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:813)
	at android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:974)
	at org.unfoldingword.door43client.Library.<init>(Library.java:53)
	at org.unfoldingword.door43client.API.<init>(API.java:76)
	at org.unfoldingword.door43client.Door43Client.<init>(Door43Client.java:50)
	at com.door43.translationstudio.App.getLibrary(App.java:337)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:520)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:169)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:39)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:91)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

3/8/17 3:03 PM  E/com.door43.translationstudio.services.BackupService: Could not backup en-x-demo2_phm_text_reg
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:853)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:974)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
	at org.unfoldingword.door43client.Library.getProject(Library.java:898)
	at com.door43.translationstudio.core.ArchiveDetails.parseV2Manifest(ArchiveDetails.java:166)
	at com.door43.translationstudio.core.ArchiveDetails.newInstance(ArchiveDetails.java:89)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:520)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:169)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:39)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:91)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

3/8/17 11:50 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_php_text_reg
3/8/17 11:50 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_php_text_reg
3/7/17 7:31 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en_psa_text_reg
3/7/17 7:31 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en_psa_text_reg
3/7/17 6:16 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_1ch_text_reg
3/7/17 6:16 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_1ch_text_reg
3/7/17 6:12 PM  E/ExportProjectTask: Failed to export the target translation en-x-demo1_php_text_reg
java.lang.Exception: Output file must have 'tstudio' extension
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:320)
	at com.door43.translationstudio.tasks.ExportProjectTask.start(ExportProjectTask.java:58)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/7/17 5:48 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_psa_text_reg
3/7/17 5:48 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_psa_text_reg
3/7/17 5:47 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_psa_text_reg
3/7/17 5:47 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_psa_text_reg
     

```

**Comment by PhotoNomad0** [comment]
@neutrinog - we could add a sanity check to ReviewModeAdapter.runTaskGarbageCollection(position) that position is within range of mItems.  But could there be a one off bug in the method that calls this, since we are running past the end of the list?

java.lang.IndexOutOfBoundsException: Invalid index 383, size is 383

**Comment by neutrinog** [comment]
good idea. fixed.
