### ISSUE TITLE
exporting usfm file to SD card

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1998]
Notes
======
All exports to usfm fail in build 159 (both internal and sd card)
Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 159
UDID | b65ef2f052953fdb
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Log history
======
```java
3/15/17 4:49 PM  E/com.door43.translationstudio.core.ExportUsfm: Failed to export the target translation en-x-demo1_gal_text_reg
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.close()' on a null object reference
	at com.door43.translationstudio.core.ExportUsfm.exportAsUSFM(ExportUsfm.java:155)
	at com.door43.translationstudio.core.ExportUsfm.saveToUSFM(ExportUsfm.java:51)
	at com.door43.translationstudio.tasks.ExportToUsfmTask.start(ExportToUsfmTask.java:38)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/15/17 4:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:49 PM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10137 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4048)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:291)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:271)
	at com.door43.util.SdUtils.doWeNeedToRequestSdCardAccess(SdUtils.java:149)
	at com.door43.translationstudio.ui.filechooser.FileChooserActivity$5.onClick(FileChooserActivity.java:167)
	at android.view.View.performClick(View.java:4809)
	at android.view.View$PerformClick.run(View.java:20123)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

3/15/17 4:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:49 PM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10137 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4048)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:291)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:271)
	at com.door43.util.SdUtils.removeSdCardWriteAccess(SdUtils.java:218)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$8.run(DeveloperToolsActivity.java:164)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$4.onItemClick(DeveloperToolsActivity.java:118)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1185)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3222)
	at android.widget.AbsListView$3.run(AbsListView.java:4138)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

3/15/17 4:48 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:48 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:46 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:44 PM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10137 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4048)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:291)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:271)
	at com.door43.util.SdUtils.doWeNeedToRequestSdCardAccess(SdUtils.java:149)
	at com.door43.translationstudio.ui.filechooser.FileChooserActivity$5.onClick(FileChooserActivity.java:167)
	at android.view.View.performClick(View.java:4809)
	at android.view.View$PerformClick.run(View.java:20123)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

3/15/17 4:44 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:44 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:44 PM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10137 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4048)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:291)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:271)
	at com.door43.util.SdUtils.removeSdCardWriteAccess(SdUtils.java:218)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$8.run(DeveloperToolsActivity.java:164)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$4.onItemClick(DeveloperToolsActivity.java:118)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1185)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3222)
	at android.widget.AbsListView$3.run(AbsListView.java:4138)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

3/15/17 4:44 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:44 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:42 PM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10137 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4048)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:291)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:271)
	at com.door43.util.SdUtils.doWeNeedToRequestSdCardAccess(SdUtils.java:149)
	at com.door43.translationstudio.ui.filechooser.FileChooserActivity$5.onClick(FileChooserActivity.java:167)
	at android.view.View.performClick(View.java:4809)
	at android.view.View$PerformClick.run(View.java:20123)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

3/15/17 4:41 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:41 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:41 PM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10137 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4048)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:291)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:271)
	at com.door43.util.SdUtils.removeSdCardWriteAccess(SdUtils.java:218)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$8.run(DeveloperToolsActivity.java:164)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$4.onItemClick(DeveloperToolsActivity.java:118)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1185)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3222)
	at android.widget.AbsListView$3.run(AbsListView.java:4138)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

3/15/17 4:41 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:40 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:40 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:39 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:39 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:36 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:36 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:36 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:30 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:30 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:30 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:30 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_1ch_text_reg
3/15/17 4:30 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_1ch_text_reg
3/15/17 4:30 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:30 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:29 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:29 PM  E/com.door43.translationstudio.services.BackupService: Could not backup en-x-demo2_3jn_text_reg
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:340)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:305)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:534)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:169)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:39)
	at com.door43.translationstudio.services.BackupService$2.run(BackupService.java:241)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.os.HandlerThread.run(HandlerThread.java:61)

3/15/17 4:26 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:26 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:26 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:26 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:26 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:26 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_php_text_reg
3/15/17 4:25 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:24 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:24 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:24 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:24 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:24 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_php_text_reg
3/15/17 4:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_php_text_reg
3/15/17 4:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:22 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:22 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:21 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:21 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:20 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:20 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:20 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:19 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_php_text_reg
3/15/17 3:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_php_text_reg
3/15/17 3:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_php_text_reg
3/15/17 3:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:32 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:28 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:28 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:27 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:27 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:27 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:27 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:27 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 3:27 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_php_text_reg
     

```

**Comment by PhotoNomad0** [comment]
@cckozie - need some help reproducing this.  This looks like an export to pdf failure.  Installed build 159 and can export to PDF, USFM, and project.

**Comment by PhotoNomad0** [comment]
@cckozie - this looks like granting access to SD card failed, and then tried to print to PDF.

**Comment by PhotoNomad0** [comment]
@cckozie - this looks like granting access to SD card failed, and then tried to export USFM.

**Comment by PhotoNomad0** [comment]
@cckozie - are you exporting an empty document here?  I only get this behavior in that case.

**Comment by PhotoNomad0** [comment]
check in build 161

**Comment by cckozie** [comment]
@PhotoNomad0 Yes, after looking at it I do believe that I was attempting to export an empty project. Since the export to pdf and export to project file both worked, it made me think that export to usfm was broken. Could we indicate in the failure message that it failed because there was no translated text in the project?
