### ISSUE TITLE
source text for this chunk does not get rendered

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2002]
Notes
======
source text for this chunk does not get rendered

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 162
UDID | b65ef2f052953fdb
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Log history
======
```java
3/16/17 1:13 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_php_text_reg
3/16/17 1:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_php_text_reg
3/16/17 1:10 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:10 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:10 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:10 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:08 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_php_text_reg
3/16/17 1:05 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:05 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:05 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:05 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:05 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:05 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:04 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:04 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:04 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:03 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:03 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:03 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_php_text_reg
3/16/17 11:25 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 11:25 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 11:25 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:46 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:46 AM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10137 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4048)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:291)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:271)
	at com.door43.util.SdUtils.doWeNeedToRequestSdCardAccess(SdUtils.java:149)
	at com.door43.translationstudio.ui.filechooser.FileChooserActivity$5.onClick(FileChooserActivity.java:167)
	at android.view.View.performClick(View.java:4809)
	at android.view.View$PerformClick.run(View.java:20123)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

3/16/17 10:46 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:46 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:46 AM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10137 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4048)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:291)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:271)
	at com.door43.util.SdUtils.removeSdCardWriteAccess(SdUtils.java:218)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$8.run(DeveloperToolsActivity.java:164)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$4.onItemClick(DeveloperToolsActivity.java:118)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1185)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3222)
	at android.widget.AbsListView$3.run(AbsListView.java:4138)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

3/16/17 10:45 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:45 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:45 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:43 AM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10137 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4048)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:291)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:271)
	at com.door43.util.SdUtils.doWeNeedToRequestSdCardAccess(SdUtils.java:149)
	at com.door43.translationstudio.ui.filechooser.FileChooserActivity$5.onClick(FileChooserActivity.java:167)
	at android.view.View.performClick(View.java:4809)
	at android.view.View$PerformClick.run(View.java:20123)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

3/16/17 10:43 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:43 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:43 AM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10137 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4048)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:291)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:271)
	at com.door43.util.SdUtils.removeSdCardWriteAccess(SdUtils.java:218)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$8.run(DeveloperToolsActivity.java:164)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$4.onItemClick(DeveloperToolsActivity.java:118)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1185)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3222)
	at android.widget.AbsListView$3.run(AbsListView.java:4138)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

3/16/17 10:43 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:43 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:30 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:26 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:25 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:25 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:25 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:25 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:25 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:25 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:24 AM  E/com.door43.translationstudio.core.ExportUsfm: Failed to export the target translation en-x-demo1_luk_text_reg
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.close()' on a null object reference
	at com.door43.translationstudio.core.ExportUsfm.exportAsUSFM(ExportUsfm.java:155)
	at com.door43.translationstudio.core.ExportUsfm.saveToUSFM(ExportUsfm.java:51)
	at com.door43.translationstudio.tasks.ExportToUsfmTask.start(ExportToUsfmTask.java:38)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/16/17 10:24 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:24 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:24 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:24 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:23 AM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10137 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4048)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:291)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:271)
	at com.door43.util.SdUtils.doWeNeedToRequestSdCardAccess(SdUtils.java:149)
	at com.door43.translationstudio.ui.filechooser.FileChooserActivity$5.onClick(FileChooserActivity.java:167)
	at android.view.View.performClick(View.java:4809)
	at android.view.View$PerformClick.run(View.java:20123)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

3/16/17 10:23 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:23 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 10:23 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 6:03 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 12:01 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 6:57 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:58 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:56 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:55 PM  E/com.door43.translationstudio.core.ExportUsfm: Failed to export the target translation en-x-demo1_gal_text_reg
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.close()' on a null object reference
	at com.door43.translationstudio.core.ExportUsfm.exportAsUSFM(ExportUsfm.java:155)
	at com.door43.translationstudio.core.ExportUsfm.saveToUSFM(ExportUsfm.java:51)
	at com.door43.translationstudio.tasks.ExportToUsfmTask.start(ExportToUsfmTask.java:38)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/15/17 4:55 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:55 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:55 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:55 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:55 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:55 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_php_text_reg
3/15/17 4:55 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:55 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:55 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/15/17 4:55 PM  E/com.door43.translationstudio.core.ExportUsfm: Failed to export the target translation en-x-demo1_gal_text_reg
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.close()' on a null object reference
	at com.door43.translationstudio.core.ExportUsfm.exportAsUSFM(ExportUsfm.java:155)
	at com.door43.translationstudio.core.ExportUsfm.saveToUSFM(ExportUsfm.java:51)
	at com.door43.translationstudio.tasks.ExportToUsfmTask.start(ExportToUsfmTask.java:38)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/15/17 4:55 PM  E/com.door43.util.SdUtils: Failed to Apply Permissions
java.lang.SecurityException: No persistable permission grants found for UID 10137 and Uri 0 @ content://com.android.externalstorage.documents/tree/Fail_Me
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4048)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at com.door43.util.SdUtils.applyPermissions(SdUtils.java:291)
	at com.door43.util.SdUtils.restoreSdCardWriteAccess(SdUtils.java:271)
	at com.door43.util.SdUtils.removeSdCardWriteAccess(SdUtils.java:218)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$8.run(DeveloperToolsActivity.java:164)
	at com.door43.translationstudio.ui.devtools.DeveloperToolsActivity$4.onItemClick(DeveloperToolsActivity.java:118)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1185)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3222)
	at android.widget.AbsListView$3.run(AbsListView.java:4138)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

3/15/17 4:54 PM  E/com.door43.translationstudio.core.ExportUsfm: Failed to export the target translation en-x-demo1_gal_text_reg
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.close()' on a null object reference
	at com.door43.translationstudio.core.ExportUsfm.exportAsUSFM(ExportUsfm.java:155)
	at com.door43.translationstudio.core.ExportUsfm.saveToUSFM(ExportUsfm.java:51)
	at com.door43.translationstudio.tasks.ExportToUsfmTask.start(ExportToUsfmTask.java:38)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/15/17 4:54 PM  E/com.door43.translationstudio.core.ExportUsfm: Failed to export the target translation en-x-demo1_gal_text_reg
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.close()' on a null object reference
	at com.door43.translationstudio.core.ExportUsfm.exportAsUSFM(ExportUsfm.java:155)
	at com.door43.translationstudio.core.ExportUsfm.saveToUSFM(ExportUsfm.java:51)
	at com.door43.translationstudio.tasks.ExportToUsfmTask.start(ExportToUsfmTask.java:38)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/15/17 4:53 PM  E/com.door43.translationstudio.core.ExportUsfm: Failed to export the target translation en-x-demo1_gal_text_reg
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.close()' on a null object reference
	at com.door43.translationstudio.core.ExportUsfm.exportAsUSFM(ExportUsfm.java:155)
	at com.door43.translationstudio.core.ExportUsfm.saveToUSFM(ExportUsfm.java:51)
	at com.door43.translationstudio.tasks.ExportToUsfmTask.start(ExportToUsfmTask.java:38)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/15/17 4:53 PM  E/com.door43.translationstudio.core.ExportUsfm: Failed to export the target translation en-x-demo1_gal_text_reg
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.close()' on a null object reference
	at com.door43.translationstudio.core.ExportUsfm.exportAsUSFM(ExportUsfm.java:155)
	at com.door43.translationstudio.core.ExportUsfm.saveToUSFM(ExportUsfm.java:51)
	at com.door43.translationstudio.tasks.ExportToUsfmTask.start(ExportToUsfmTask.java:38)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/15/17 4:52 PM  E/com.door43.translationstudio.core.ExportUsfm: Failed to export the target translation en-x-demo1_gal_text_reg
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.close()' on a null object reference
	at com.door43.translationstudio.core.ExportUsfm.exportAsUSFM(ExportUsfm.java:155)
	at com.door43.translationstudio.core.ExportUsfm.saveToUSFM(ExportUsfm.java:51)
	at com.door43.translationstudio.tasks.ExportToUsfmTask.start(ExportToUsfmTask.java:38)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/15/17 4:52 PM  E/com.door43.translationstudio.core.ExportUsfm: Failed to export the target translation en-x-demo1_gal_text_reg
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.close()' on a null object reference
	at com.door43.translationstudio.core.ExportUsfm.exportAsUSFM(ExportUsfm.java:155)
	at com.door43.translationstudio.core.ExportUsfm.saveToUSFM(ExportUsfm.java:51)
	at com.door43.translationstudio.tasks.ExportToUsfmTask.start(ExportToUsfmTask.java:38)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/15/17 4:51 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
     

```

**Comment by cckozie** [comment]
Several chunks never got rendered even after waiting for several minutes (actually, all chunks after chapter 2 chunk 5). Switched to read mode and back to review mode, no change.
If I switch out of the mode where only chunks with conflicts are displayed and then switch back, it usually renders one more chunk. Even after closing and reopening the project, most of the chunks still show the spinning arrow and not the source text.
![screenshot_2017-03-16-13-13-26](https://cloud.githubusercontent.com/assets/8171759/24012079/b502c626-0a4a-11e7-81c5-d2d5687311b4.png)

**Comment by neutrinog** [comment]
@cckozie can you send a copy of the project you are working with?

**Comment by cckozie** [comment]
[en-x-demo2_php_text_reg_conflicts.tstudio.zip](https://github.com/unfoldingWord-dev/ts-android/files/859895/en-x-demo2_php_text_reg_conflicts.tstudio.zip)

**Comment by PhotoNomad0** [comment]
@neutrinog - I see an error when I try to import this project:

03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'org.eclipse.jgit.revwalk.RevTree org.eclipse.jgit.revwalk.RevCommit.getTree()' on a null object reference
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at org.eclipse.jgit.merge.RecursiveMerger.getBaseCommit(RecursiveMerger.java:197)
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at org.eclipse.jgit.merge.RecursiveMerger.getBaseCommit(RecursiveMerger.java:125)
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at org.eclipse.jgit.merge.ThreeWayMerger.mergeBase(ThreeWayMerger.java:132)
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at org.eclipse.jgit.merge.ResolveMerger.mergeImpl(ResolveMerger.java:301)
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at org.eclipse.jgit.merge.Merger.merge(Merger.java:203)
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at org.eclipse.jgit.merge.Merger.merge(Merger.java:156)
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at org.eclipse.jgit.merge.ThreeWayMerger.merge(ThreeWayMerger.java:114)
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at org.eclipse.jgit.api.MergeCommand.call(MergeCommand.java:342)
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at com.door43.translationstudio.core.TargetTranslation.merge(TargetTranslation.java:1206)
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at com.door43.translationstudio.core.Translator.importArchive(Translator.java:465)
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at com.door43.translationstudio.tasks.ImportProjectFromUriTask.start(ImportProjectFromUriTask.java:55)
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
03-23 10:39:21.706 17615-17788/com.translationstudio.androidapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-23 10:39:21.707 17615-17788/com.translationstudio.androidapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-23 10:39:21.707 17615-17788/com.translationstudio.androidapp W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by neutrinog** [comment]
@cckozie figured out the issue. There were actually several different bugs you didn't even catch that had the same root.

* footnotes were broken
* source was broken
* resources were broken

**Comment by cckozie** [comment]
I was just saving those for later:)

**Comment by cckozie** [comment]
I see a change in behavior, but it is worse. For the first 70 seconds neither the source or translation text is rendered.
![screenshot_2017-03-24-10-29-54](https://cloud.githubusercontent.com/assets/8171759/24298899/6eee780c-1075-11e7-8420-5f34b0ee2b82.png)

Then the target text is rendered, but the source is still empty after several more minutes.
![screenshot_2017-03-24-10-32-28](https://cloud.githubusercontent.com/assets/8171759/24298966/a31997b0-1075-11e7-8d65-98a8626d303c.png)

**Comment by neutrinog** [comment]
@cckozie I don't have any devices that old to test on.

**Comment by neutrinog** [comment]
@PhotoNomad0 do you have a 4.1.1 device?

**Comment by cckozie** [comment]
Sorry, it's really a 4.4.2 device.

**Comment by neutrinog** [comment]
@cckozie I got an emulator running. The app runs flawlessly. Even giving it a single core and setting the memory super low it's still zippy fast. So it's not much help.

**Comment by PhotoNomad0** [comment]
Tried this on an old Samsung Galaxy S2 running android 4.0.4.  It rendered sources, but took about 15 seconds.

**Comment by neutrinog** [comment]
@cckozie this is very likely related to the threading fixes I just made. Can you check this again?
