### ISSUE TITLE
device had gone to sleep with project open. wok...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2003]
Notes
======
device had gone to sleep with project open. woke it up and it crashed

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 162
UDID | b65ef2f052953fdb
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Stack trace
======
```java
java.lang.IllegalArgumentException: Progress (-1) must be between 0 and 100
	at com.filippudak.ProgressPieView.ProgressPieView.setProgress(ProgressPieView.java:307)
	at com.door43.translationstudio.ui.home.TargetTranslationAdapter$ViewHolder.setProgress(TargetTranslationAdapter.java:295)
	at com.door43.translationstudio.ui.home.TargetTranslationAdapter.getView(TargetTranslationAdapter.java:188)
	at android.widget.AbsListView.obtainView(AbsListView.java:2464)
	at android.widget.ListView.onMeasure(ListView.java:1166)
	at android.view.View.measure(View.java:17776)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:17776)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1205)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:631)
	at android.view.View.measure(View.java:17776)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at android.view.View.measure(View.java:17776)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:17776)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:963)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:17776)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
	at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
	at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:786)
	at android.view.View.measure(View.java:17776)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
	at android.view.View.measure(View.java:17776)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at android.view.View.measure(View.java:17776)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at android.view.View.measure(View.java:17776)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:17776)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2641)
	at android.view.View.measure(View.java:17776)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2366)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1381)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1605)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1259)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6455)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
	at android.view.Choreographer.doFrame(Choreographer.java:572)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

```
Log history
======
```java
3/16/17 1:30 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:30 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:26 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:22 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:22 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:18 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 1:14 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
     

```

**Comment by cckozie** [comment]
Pretty sure this is fixed in Travis build 1327.
