### ISSUE TITLE
Source text download stuck in failure mode after canceling

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2004]
Selected English then OBS source to be downloaded.
Canceled the download mid cycle
Screen shows both check mark and red warning icon
Click Download button and immediately get the Download Errors dialog.
After going back to the home screen and restarting the Download Source process I still immediately get the error message after clicking Download button.
I still get that behavior after closing and reopening the app.
Same behavior after going into Android settings and force stopping the app.

**Comment by cckozie** [comment]
See issue #2005 for log file

**Comment by PhotoNomad0** [comment]
@cckozie - seems to be working right for me.  Unfortunately there is not anything helpful in the log.

**Comment by cckozie** [comment]
Not sure it's helpful, but I just cleared the log, set to info level, and sent a feedback after attempting the download again. See #2007

**Comment by PhotoNomad0** [comment]
@neutrinog 

One issue in the log seems to be that ResourceContainer.load() is throwing an exception that toc.yml is missing.  It looks like ContainerTools.convertResource() is no longer creating the toc.yml.

**Comment by PhotoNomad0** [comment]
I have captured one exception when cancel occurs during download:

`03-17 09:05:00.543 3553-3714/com.translationstudio.androidapp E/DownloadResourceContainersTask: OBS Words download Helps Failed: en_bible-obs_tw
                                                                                                java.io.InterruptedIOException
                                                                                                    at com.android.okio.Deadline.throwIfReached(Deadline.java:56)
                                                                                                    at com.android.okio.Okio$2.read(Okio.java:110)
                                                                                                    at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
                                                                                                    at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:499)
                                                                                                    at com.android.okio.RealBufferedSource.exhausted(RealBufferedSource.java:58)
                                                                                                    at com.android.okio.InflaterSource.refill(InflaterSource.java:96)
                                                                                                    at com.android.okio.InflaterSource.read(InflaterSource.java:62)
                                                                                                    at com.android.okio.GzipSource.read(GzipSource.java:75)
                                                                                                    at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                                                                    at java.io.InputStream.read(InputStream.java:162)
                                                                                                    at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
                                                                                                    at java.io.BufferedInputStream.read(BufferedInputStream.java:295)
                                                                                                    at java.io.InputStream.read(InputStream.java:162)
                                                                                                    at org.unfoldingword.tools.http.Request.download(Request.java:178)
                                                                                                    at org.unfoldingword.door43client.API.downloadFutureCompatibleResourceContainer(API.java:398)
                                                                                                    at org.unfoldingword.door43client.API.downloadResourceContainer(API.java:358)
                                                                                                    at org.unfoldingword.door43client.Door43Client.download(Door43Client.java:122)
                                                                                                    at com.door43.translationstudio.tasks.DownloadResourceContainersTask.downloadHelps(DownloadResourceContainersTask.java:175)
                                                                                                    at com.door43.translationstudio.tasks.DownloadResourceContainersTask.downloadTranlationWords(DownloadResourceContainersTask.java:142)
                                                                                                    at com.door43.translationstudio.tasks.DownloadResourceContainersTask.start(DownloadResourceContainersTask.java:94)
                                                                                                    at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
                                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                    at java.lang.Thread.run(Thread.java:818)`

But it doesn't leave future downloads broken.

**Comment by cckozie** [comment]
It is better now, but there is still a repeatable problem. Again I chose to download the English source text for OBS.
Within a few seconds of clicking on the Download button, I clicked Cancel.
Closed the Canceled dialog
Clicked the Download button
Got the Download Errors dialog
Clicking the Download button now always results in the Download Errors message
Clicking on the red warning shows this message:
![screenshot_2017-03-20-09-11-48](https://cloud.githubusercontent.com/assets/8171759/24103887/afefb264-0d4e-11e7-8bae-600e75f17387.png)

If I exit back to the Choose Category screen and then again select English OBS, it now works.

**Comment by neutrinog** [comment]
sounds like some io stream might not be getting closed right away.

**Comment by neutrinog** [comment]
@cckozie I cannot reproduce your error exactly.

* click download
* cancel download right away (before it begins downloading en_bible-obs_tw)
* click download again
* Shows the error "0 source text have been successfully downloaded... 1 source downloads have failed"
* Click download again
* Downloads successfully.

**Comment by cckozie** [comment]
Running Travis build 1318 I can still replicate the issue but it takes quite a few tries, and after it gets into the failure mode, the worst case I've seen is that it recovers after two mode tries just clicking the Download button. We'll call it good enough.
