### ISSUE TITLE
another log for issue 2004

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2011]
Notes
======
another log for issue 2004

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 163
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Log history
======
```java
3/17/17 10:26 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/17/17 10:26 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/17/17 10:25 AM  E/DownloadSourcesDialog: Download failed: en_obs_obs
3/17/17 10:25 AM  E/DownloadResourceContainersTask: download source Failed: en_obs_obs
java.io.FileNotFoundException: /storage/emulated/0/translationStudio/resource_containers/en_obs_obs/package.json: open failed: EBUSY (Device or resource busy)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:127)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
	at org.unfoldingword.resourcecontainer.FileUtil.writeStringToFile(FileUtil.java:68)
	at org.unfoldingword.resourcecontainer.ContainerTools.convertResource(ContainerTools.java:106)
	at org.unfoldingword.door43client.API.convertLegacyResource(API.java:503)
	at org.unfoldingword.door43client.API.downloadResourceContainer(API.java:367)
	at org.unfoldingword.door43client.Door43Client.download(Door43Client.java:122)
	at com.door43.translationstudio.tasks.DownloadResourceContainersTask.start(DownloadResourceContainersTask.java:69)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: EBUSY (Device or resource busy)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	... 13 more

3/17/17 10:25 AM  I/DownloadResourceContainersTask: Loading ID: en_obs_obs
3/17/17 10:25 AM  I/DownloadSourcesDialog: DownloadResourceContainersTask was cancelled
3/17/17 10:25 AM  I/DownloadResourceContainersTask: download canceled before translation words: en_obs_obs
3/17/17 10:25 AM  I/DownloadResourceContainersTask: download Success: en_obs_obs
3/17/17 10:25 AM  I/DownloadResourceContainersTask: Loading ID: en_obs_obs
3/17/17 10:25 AM  I/DownloadSourcesAdapter: Found 749 sources
3/17/17 10:24 AM  I/DownloadSourcesDialog: Received: en_obs_obs
3/17/17 10:24 AM  I/DownloadResourceContainersTask: Questions download Success: en_obs_tq
3/17/17 10:24 AM  I/DownloadResourceContainersTask: Loading Questions ID: en_obs_tq
3/17/17 10:24 AM  I/DownloadResourceContainersTask: Notes download Success: en_obs_tn
3/17/17 10:24 AM  I/DownloadResourceContainersTask: Loading Notes ID: en_obs_tn
3/17/17 10:24 AM  I/DownloadResourceContainersTask: OBS Words download Success: en_bible-obs_tw
3/17/17 10:24 AM  I/DownloadResourceContainersTask: Loading OBS Words ID: en_bible-obs_tw
3/17/17 10:24 AM  I/DownloadResourceContainersTask: download Success: en_obs_obs
3/17/17 10:24 AM  I/DownloadResourceContainersTask: Loading ID: en_obs_obs
3/17/17 10:24 AM  I/DownloadSourcesAdapter: Found 749 sources
3/17/17 10:23 AM  E/DownloadSourcesDialog: Download failed: en_obs_obs
3/17/17 10:23 AM  E/DownloadResourceContainersTask: download source Failed: en_obs_obs
java.io.FileNotFoundException: /storage/emulated/0/translationStudio/resource_containers/en_obs_obs/package.json: open failed: EBUSY (Device or resource busy)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:127)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
	at org.unfoldingword.resourcecontainer.FileUtil.writeStringToFile(FileUtil.java:68)
	at org.unfoldingword.resourcecontainer.ContainerTools.convertResource(ContainerTools.java:106)
	at org.unfoldingword.door43client.API.convertLegacyResource(API.java:503)
	at org.unfoldingword.door43client.API.downloadResourceContainer(API.java:367)
	at org.unfoldingword.door43client.Door43Client.download(Door43Client.java:122)
	at com.door43.translationstudio.tasks.DownloadResourceContainersTask.start(DownloadResourceContainersTask.java:69)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: EBUSY (Device or resource busy)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	... 13 more

3/17/17 10:23 AM  I/DownloadResourceContainersTask: Loading ID: en_obs_obs
3/17/17 10:23 AM  E/DownloadSourcesDialog: Download failed: en_obs_obs
3/17/17 10:23 AM  E/DownloadResourceContainersTask: download source Failed: en_obs_obs
java.io.FileNotFoundException: /storage/emulated/0/translationStudio/resource_containers/en_obs_obs/package.json: open failed: EBUSY (Device or resource busy)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:127)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
	at org.unfoldingword.resourcecontainer.FileUtil.writeStringToFile(FileUtil.java:68)
	at org.unfoldingword.resourcecontainer.ContainerTools.convertResource(ContainerTools.java:106)
	at org.unfoldingword.door43client.API.convertLegacyResource(API.java:503)
	at org.unfoldingword.door43client.API.downloadResourceContainer(API.java:367)
	at org.unfoldingword.door43client.Door43Client.download(Door43Client.java:122)
	at com.door43.translationstudio.tasks.DownloadResourceContainersTask.start(DownloadResourceContainersTask.java:69)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: EBUSY (Device or resource busy)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	... 13 more

3/17/17 10:23 AM  I/DownloadResourceContainersTask: Loading ID: en_obs_obs
3/17/17 10:23 AM  I/DownloadSourcesDialog: DownloadResourceContainersTask was cancelled
3/17/17 10:23 AM  I/DownloadResourceContainersTask: download canceled before translation words: en_obs_obs
3/17/17 10:23 AM  I/DownloadResourceContainersTask: download Success: en_obs_obs
3/17/17 10:23 AM  I/DownloadResourceContainersTask: Loading ID: en_obs_obs
3/17/17 10:23 AM  I/DownloadSourcesDialog: DownloadResourceContainersTask was cancelled
3/17/17 10:23 AM  I/DownloadResourceContainersTask: download canceled before translation notes: en_obs_obs
3/17/17 10:23 AM  I/DownloadResourceContainersTask: OBS Words download Success: en_bible-obs_tw
3/17/17 10:23 AM  I/DownloadResourceContainersTask: Loading OBS Words ID: en_bible-obs_tw
3/17/17 10:23 AM  I/DownloadResourceContainersTask: download Success: en_obs_obs
3/17/17 10:23 AM  I/DownloadResourceContainersTask: Loading ID: en_obs_obs
3/17/17 10:23 AM  I/DownloadSourcesAdapter: Found 749 sources
3/17/17 10:23 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/17/17 10:23 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_luk_text_reg
3/17/17 10:23 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_1ch_text_reg
3/17/17 10:23 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg
3/17/17 10:23 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/17/17 10:22 AM  E/DownloadSourcesDialog: Download failed: en_obs_obs
3/17/17 10:22 AM  E/DownloadResourceContainersTask: download source Failed: en_obs_obs
java.io.FileNotFoundException: /storage/emulated/0/translationStudio/resource_containers/en_obs_obs/package.json: open failed: EBUSY (Device or resource busy)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:127)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
	at org.unfoldingword.resourcecontainer.FileUtil.writeStringToFile(FileUtil.java:68)
	at org.unfoldingword.resourcecontainer.ContainerTools.convertResource(ContainerTools.java:106)
	at org.unfoldingword.door43client.API.convertLegacyResource(API.java:503)
	at org.unfoldingword.door43client.API.downloadResourceContainer(API.java:367)
	at org.unfoldingword.door43client.Door43Client.download(Door43Client.java:122)
	at com.door43.translationstudio.tasks.DownloadResourceContainersTask.start(DownloadResourceContainersTask.java:69)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: EBUSY (Device or resource busy)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	... 13 more

3/17/17 10:22 AM  E/DownloadSourcesDialog: Download failed: en_obs_obs
3/17/17 10:22 AM  E/DownloadResourceContainersTask: download source Failed: en_obs_obs
java.io.FileNotFoundException: /storage/emulated/0/translationStudio/resource_containers/en_obs_obs/package.json: open failed: EBUSY (Device or resource busy)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:127)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
	at org.unfoldingword.resourcecontainer.FileUtil.writeStringToFile(FileUtil.java:68)
	at org.unfoldingword.resourcecontainer.ContainerTools.convertResource(ContainerTools.java:106)
	at org.unfoldingword.door43client.API.convertLegacyResource(API.java:503)
	at org.unfoldingword.door43client.API.downloadResourceContainer(API.java:367)
	at org.unfoldingword.door43client.Door43Client.download(Door43Client.java:122)
	at com.door43.translationstudio.tasks.DownloadResourceContainersTask.start(DownloadResourceContainersTask.java:69)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: EBUSY (Device or resource busy)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	... 13 more

3/15/17 11:24 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_luk_text_reg
3/15/17 11:24 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_luk_text_reg
3/11/17 8:46 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_1ch_text_reg
3/11/17 8:46 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_1ch_text_reg
3/8/17 1:02 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes for en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:203)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1069)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 4 more

3/8/17 1:02 PM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes for en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:203)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1069)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 4 more

3/8/17 1:02 PM  E/TargetTranslation: Failed to stage changes for en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1051)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 3 more

3/8/17 1:02 PM  E/TargetTranslation: Failed to stage changes for en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1051)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 3 more

3/8/17 5:46 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes for en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:203)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1069)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 4 more

3/8/17 5:46 AM  E/TargetTranslation: Failed to stage changes for en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1051)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 3 more

3/8/17 4:51 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes for en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:203)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1069)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 4 more

3/8/17 4:51 AM  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes for en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of commit command
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:317)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1069)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:235)
	... 3 more

3/8/17 4:51 AM  E/TargetTranslation: Failed to stage changes for en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1051)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 3 more

3/8/17 4:51 AM  E/TargetTranslation: Failed to stage changes for en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1051)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 3 more

3/8/17 4:51 AM  E/TargetTranslation: Failed to stage changes for en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1051)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 3 more

3/8/17 4:50 AM  E/TargetTranslation: Failed to stage changes for en-x-demo1_psa_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1051)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 3 more

3/7/17 6:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
3/7/17 6:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
3/7/17 6:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
3/7/17 6:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
3/7/17 6:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
3/7/17 6:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
3/7/17 6:49 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
3/7/17 6:49 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation en-x-demo1_psa_text_reg
3/7/17 6:49 PM  W/com.door43.translationstudio.ui.translate.TargetTranslationActivity: The library was not deployed.
3/7/17 6:49 PM  W/com.door43.translationstudio.ui.home.HomeActivity: The library was not deployed.
     

```

**Comment by cckozie** [comment]
After canceling a source text download, retrying that download immediately fails. But now when I exit back to the home screen and then go back to downloads, it does succeed.
