### ISSUE TITLE
log for #2004, device with original failure upg...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2012]
Notes
======
log for #2004, device with original failure upgraded to build 163. Still fails immediately.

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 163
UDID | b65ef2f052953fdb
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Log history
======
```java
3/17/17 10:53 AM  E/DownloadSourcesDialog: Download failed: en_obs_obs
3/17/17 10:53 AM  E/DownloadResourceContainersTask: download source Failed: en_obs_obs
java.lang.NullPointerException: Attempt to get length of null array
	at org.unfoldingword.door43client.FileUtil.deleteQuietly(FileUtil.java:157)
	at org.unfoldingword.door43client.API.downloadFutureCompatibleResourceContainer(API.java:393)
	at org.unfoldingword.door43client.API.downloadResourceContainer(API.java:358)
	at org.unfoldingword.door43client.Door43Client.download(Door43Client.java:122)
	at com.door43.translationstudio.tasks.DownloadResourceContainersTask.start(DownloadResourceContainersTask.java:69)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/17/17 10:53 AM  I/DownloadResourceContainersTask: Loading ID: en_obs_obs
3/17/17 10:53 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/17/17 10:53 AM  I/com.door43.translationstudio.services.BackupService: en-x-demo2_php_text_reg backed up
3/17/17 10:53 AM  E/DownloadSourcesDialog: Download failed: en_obs_obs
3/17/17 10:53 AM  E/DownloadResourceContainersTask: download source Failed: en_obs_obs
java.lang.NullPointerException: Attempt to get length of null array
	at org.unfoldingword.door43client.FileUtil.deleteQuietly(FileUtil.java:157)
	at org.unfoldingword.door43client.API.downloadFutureCompatibleResourceContainer(API.java:393)
	at org.unfoldingword.door43client.API.downloadResourceContainer(API.java:358)
	at org.unfoldingword.door43client.Door43Client.download(Door43Client.java:122)
	at com.door43.translationstudio.tasks.DownloadResourceContainersTask.start(DownloadResourceContainersTask.java:69)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

3/17/17 10:53 AM  I/DownloadResourceContainersTask: Loading ID: en_obs_obs
3/17/17 10:53 AM  I/com.door43.translationstudio.services.BackupService: fr_1jn_text_reg backed up
3/17/17 10:53 AM  I/DownloadSourcesAdapter: Found 832 sources
3/17/17 10:53 AM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_php_text_ulb backed up
3/17/17 10:53 AM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_obs_text_obs backed up
3/17/17 10:53 AM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_tit_text_reg backed up
3/17/17 10:53 AM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_mrk_text_reg backed up
3/17/17 10:53 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 10:53 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 10:53 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 10:53 AM  I/com.door43.translationstudio.services.BackupService: en_obs_text_obs backed up
3/17/17 10:53 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo2_php_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_jhn_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/fr_1jn_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_luk_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_act_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo2_php_text_ulb
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_obs_text_obs
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_mat_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_gal_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_tit_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_mrk_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en_obs_text_obs
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_1ch_text_reg
3/17/17 10:53 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_php_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/aa_php_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo2_3jn_text_reg
3/17/17 10:53 AM  I/com.door43.translationstudio.services.BackupService: Skipping invalid translation: aa_php_text_reg
3/17/17 10:53 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 10:53 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_phm_text_reg
3/17/17 10:53 AM  I/com.door43.translationstudio.services.BackupService: en-x-demo2_3jn_text_reg backed up
3/17/17 10:53 AM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_phm_text_reg backed up
3/17/17 10:53 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/17/17 10:52 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 10:52 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 10:52 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 10:52 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 10:52 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 10:52 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_php_text_reg
3/17/17 10:19 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/17/17 10:19 AM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_php_text_ulb backed up
3/17/17 10:19 AM  I/com.door43.translationstudio.services.BackupService: Skipping invalid translation: aa_php_text_reg
3/17/17 10:19 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 10:19 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/17/17 10:19 AM  E/DownloadSourcesDialog: Download failed: en_obs_obs
3/17/17 10:19 AM  I/DownloadResourceContainersTask: download Failed: en_obs_obs
3/17/17 10:19 AM  I/DownloadResourceContainersTask: Loading ID: en_obs_obs
3/17/17 10:19 AM  I/DownloadSourcesAdapter: Found 832 sources
3/17/17 10:18 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 10:18 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 6:10 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/17/17 6:06 AM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_php_text_ulb backed up
3/17/17 6:04 AM  I/com.door43.translationstudio.services.BackupService: Skipping invalid translation: aa_php_text_reg
3/17/17 6:04 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 6:04 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/17/17 6:04 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 6:04 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 12:09 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/17/17 12:06 AM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_php_text_ulb backed up
3/17/17 12:04 AM  I/com.door43.translationstudio.services.BackupService: Skipping invalid translation: aa_php_text_reg
3/17/17 12:04 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 12:04 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/17/17 12:03 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/17/17 12:03 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 6:13 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/16/17 6:11 PM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_php_text_ulb backed up
3/16/17 6:05 PM  I/com.door43.translationstudio.services.BackupService: Skipping invalid translation: aa_php_text_reg
3/16/17 6:05 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 6:03 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/16/17 6:03 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 6:03 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 2:50 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/16/17 2:47 PM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_php_text_ulb backed up
3/16/17 2:44 PM  I/com.door43.translationstudio.services.BackupService: Skipping invalid translation: aa_php_text_reg
3/16/17 2:44 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 2:44 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/16/17 2:43 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/16/17 2:42 PM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_php_text_ulb backed up
3/16/17 2:42 PM  I/com.door43.translationstudio.services.BackupService: Skipping invalid translation: aa_php_text_reg
3/16/17 2:42 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
3/16/17 2:42 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/16/17 2:42 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/16/17 2:42 PM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_php_text_ulb backed up
     

```

**Comment by PhotoNomad0** [comment]
@neutrinog - 

```
    public static boolean deleteQuietly(File fileOrDirectory) {
        if(fileOrDirectory != null) {
            if (fileOrDirectory.isDirectory()) {
                for (File child : fileOrDirectory.listFiles()) {
```

This last line seems to be throwing the exception.

**Comment by PhotoNomad0** [comment]
@neutrinog 

maybe we need to do a check to make sure fileOrDirectory.listFiles() does not return null before starting the for loop.

**Comment by neutrinog** [comment]
this should be fixed now.
