### ISSUE TITLE
trying to open a project after installing 1307

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2027]
Notes
======
trying to open a project after installing Travis build 1307 (Android 4.4.2)

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 164
UDID | f710314c4d27668b
Android Release | 4.4.2
Android SDK | 19
Brand | rockchip
Device | rk292x
Stack trace
======
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.translationstudio.androidapp/com.door43.translationstudio.ui.translate.TargetTranslationActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
	at android.app.ActivityThread.access$800(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5017)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.door43.translationstudio.ui.translate.TargetTranslationActivity.onCreate(TargetTranslationActivity.java:222)
	at android.app.Activity.performCreate(Activity.java:5231)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
	... 11 more

```

**Comment by cckozie** [comment]
The app crashed attempting to open any of the projects I had on the device. I assume that they were created with v9, but I'm not sure. I uninstalled v11 and installed v9, then open a project, then reinstalled v11. Still crashes on every attempt to open or create a project.

**Comment by PhotoNomad0** [comment]
@cckozie - can you send one of the projects?  

I booted up my Neutab.  Was able to create a Colossians project for ghotuo.

**Comment by cckozie** [comment]
My NeuTab has Android 5.1.1. The problems were experienced on my Chromo CI2416.
After renaming both translationStudio folders I was able to create and open projects on it.
Here are a couple apps that didn't work. The 3jn project was one that was already on the device. The php project is one I was attempting to create.
[en-x-demo1_3jn_text_reg (1).zip](https://github.com/unfoldingWord-dev/ts-android/files/865407/en-x-demo1_3jn_text_reg.1.zip)
[en-x-demo1_php_text_reg (2).zip](https://github.com/unfoldingWord-dev/ts-android/files/865408/en-x-demo1_php_text_reg.2.zip)

**Comment by cckozie** [comment]
Also see log on issue #2035

**Comment by cckozie** [comment]
Works in Travis build 1334
