### ISSUE TITLE
imported project from door43, opened it and cli...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2041]
Notes
======
imported project from door43, opened it and clicked on the icon to show only chunks with conflicts.

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 164
UDID | f710314c4d27668b
Android Release | 4.4.2
Android SDK | 19
Brand | rockchip
Device | rk292x
Stack trace
======
```java
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{41ef5be0 position=0 id=-1, oldPos=0, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5251)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5433)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3488)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
	at android.view.View.layout(View.java:14838)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14838)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14838)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14838)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
	at android.view.View.layout(View.java:14838)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14838)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14838)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14838)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14838)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14838)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1996)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1753)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1005)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5750)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5017)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
	at dalvik.system.NativeStart.main(Native Method)

```
Log history
======
```java
3/24/17 10:26 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_php_text_ulb
     

```

**Comment by cckozie** [comment]
Do not see failures with Travis build 1344
