### ISSUE TITLE
source selection

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2055]
Notes
======
source selection

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 164
UDID | 213f93abcdcb049
Android Release | 4.4.2
Android SDK | 19
Brand | Allwinner
Device | astar-y3
Stack trace
======
```java
java.lang.OutOfMemoryError
	at java.lang.String.<init>(String.java:422)
	at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:642)
	at java.lang.StringBuilder.toString(StringBuilder.java:663)
	at java.io.BufferedReader.readLine(BufferedReader.java:399)
	at com.door43.util.FileUtilities.readStreamToString(FileUtilities.java:37)
	at com.door43.util.FileUtilities.readFileToString(FileUtilities.java:53)
	at com.door43.translationstudio.core.TargetTranslation.open(TargetTranslation.java:307)
	at com.door43.translationstudio.core.TargetTranslationMigrator.migrate(TargetTranslationMigrator.java:114)
	at com.door43.translationstudio.core.TargetTranslationMigrator.migrateManifest(TargetTranslationMigrator.java:57)
	at com.door43.translationstudio.core.ArchiveDetails.parseV2Manifest(ArchiveDetails.java:143)
	at com.door43.translationstudio.core.ArchiveDetails.newInstance(ArchiveDetails.java:89)
	at com.door43.translationstudio.App.backupTargetTranslation(App.java:522)
	at com.door43.translationstudio.services.BackupService.runBackup(BackupService.java:169)
	at com.door43.translationstudio.services.BackupService.access$100(BackupService.java:39)
	at com.door43.translationstudio.services.BackupService$1.run(BackupService.java:91)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

```
Log history
======
```java
3/29/17 2:18 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_rom_text_reg
3/29/17 2:18 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_rom_text_reg
3/24/17 3:31 AM  W/com.door43.translationstudio.tasks.LoginDoor43Task: gogs api responded with 401: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/users/photonomad0/tokens
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:186)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createToken(GogsAPI.java:420)
	at com.door43.translationstudio.tasks.LoginDoor43Task.start(LoginDoor43Task.java:75)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

     

```

**Comment by PhotoNomad0** [comment]
testing - crashed on low memory
