### ISSUE TITLE
most sources show as available online

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2094]
Notes
======
most sources show as available online

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 172
UDID | 1fa4d3860e18f921
Android Release | 5.1
Android SDK | 22
Brand | motorola
Device | ghost
Log history
======
```java
4/5/17 5:32 PM  E/FirstTabFragment: Error getting resource container for 'en-x-demo1_3jn_text_reg'
org.unfoldingword.resourcecontainer.errors.MissingRCException: Missing resource container
	at org.unfoldingword.resourcecontainer.ResourceContainer.open(ResourceContainer.java:201)
	at org.unfoldingword.door43client.API.openResourceContainer(API.java:632)
	at org.unfoldingword.door43client.API.openResourceContainer(API.java:610)
	at org.unfoldingword.door43client.Door43Client.open(Door43Client.java:134)
	at com.door43.translationstudio.ui.translate.FirstTabFragment.onCreateView(FirstTabFragment.java:61)
	at android.app.Fragment.performCreateView(Fragment.java:2053)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.BackStackRecord.run(BackStackRecord.java:834)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1454)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

4/5/17 5:30 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
4/5/17 5:30 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
     

```

**Comment by cckozie** [comment]
I deleted the main translationStudio folder, downloaded and installed the latest build (Travis build 1377), opened tS and imported a project from door43. When I opened the project it opened to the source selection screen with one source in the Selected group, a few sources in the Available group, and most of them in the Available Online group. This is an issue that I have seen several times in the last few days.
In trying to understand how this could occur since I had not run the Download list of available source texts, I went into explorer and noticed that there were only a few hundred files in the resource_containers folder.
I went into Android Setup and Force Stopped tS, then deleted the resource_containers folder.
I opened tS, then the imported project, and saw pretty much the same situation as before. I now have 185 items in the resource_containers folder.
Hopefully there is something in the log that will help troubleshoot this issue.

**Comment by cckozie** [comment]
I then did another Force Stop of tS. When I restarted it, it displayed the Performing Updates screen for several seconds. The imported project then opened normally, and the source selection screen shows all of the source languages as either Selected or Available. There are now 1000 items in the resource_containers folder.

**Comment by neutrinog** [comment]
linked and closing this as a duplicate.

**Comment by cckozie** [comment]
This is still a problem with Travis build 1379. At this point I have only seen it on my phone, but need to test on other devices. On my phone it is very repeatable using the following steps:
1. Delete the translationStudio folder
2. Install and open the app.
  a) Sometimes the app fully starts and takes me to the login screen.
  b) Sometime it hangs with the Performing Updates screen up
  c) In both cases, when I look in the resource_containers folder there are somewhere between 100 and 700 files. (Should be about 1000)
3. If I force stop tS, delete the resource_containers folder, and restart the app, it will recreate the resource_containers folder and load all of the source texts to it.  (I do need to force stop the app in order for it to work. If I just end it by exiting/Yes, it will not fully load the resource_containers folder)
