### ISSUE TITLE
installer Travis build 1406. crashed on opening...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2153]
Notes
======
installer Travis build 1406. crashed on opening app

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 175
UDID | aec37215833e82ce
Android Release | 5.1.1
Android SDK | 22
Brand | Allwinner
Device | octopus-bt1077
Stack trace
======
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setContentView(android.view.View)' on a null object reference
	at android.app.DialogFragment.onActivityCreated(DialogFragment.java:469)
	at android.app.Fragment.performActivityCreated(Fragment.java:2061)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:912)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.BackStackRecord.run(BackStackRecord.java:834)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:920)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:715)

```
Log history
======
```java
4/12/17 9:51 AM  I/com.door43.translationstudio.services.BackupService: Backups running every 5 minute/s
4/12/17 9:51 AM  I/com.door43.translationstudio.services.BackupService: starting backup service
4/12/17 9:51 AM  W/TargetTranslationInfoDialog: Could not find source for target com.door43.translationstudio.core.TargetTranslation@242479ac
4/12/17 9:51 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/12/17 9:51 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
4/12/17 9:51 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
4/12/17 9:50 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/12/17 9:50 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/12/17 9:50 AM  I/com.door43.translationstudio.services.BackupService: Backups running every 5 minute/s
4/12/17 9:50 AM  I/com.door43.translationstudio.services.BackupService: starting backup service
4/12/17 9:50 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_php_text_reg
4/12/17 9:50 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/gu_mat_text_reg
4/12/17 9:50 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_obs_text_obs
4/12/17 9:50 AM  W/TargetTranslationInfoDialog: Could not find source for target com.door43.translationstudio.core.TargetTranslation@13ec830
4/12/17 9:50 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
     

```

**Comment by cckozie** [comment]
After encountering issue #2152 I uninstalled tS, downloaded Travis build 1406 again, then installed it. At the end of the install it crashed when opening the app. 
The app did open upon a second launch, but still seeing the problem in 2152.

**Comment by neutrinog** [comment]
duplicate error as #2152.

**Comment by cckozie** [comment]
Still failing on my NeuTab in Travis build 1412.

**Comment by neutrinog** [comment]
@cckozie can you send me your `translationStudio` folder?

**Comment by cckozie** [comment]
@neutrinog Here ya go
[translationStudio.zip](https://github.com/unfoldingWord-dev/ts-android/files/943173/translationStudio.zip)

**Comment by cckozie** [comment]
@neutrinog This one may be fixed in Travis build 1433. I've installed it as an upgrade a couple times and also as a new install, and I have not encountered the crash. Could be that there was a problem with one of the projects that got fixed in 1433, as I also reinstalled a previous build that had crashed on opening, and it now opens fine too.

**Comment by neutrinog** [comment]
yeah, that's essentially what I was guessing because nothing I did could replicate it. But it would be nice if I could, because it's possible someone could somehow get a corrupt project.

**Comment by neutrinog** [comment]
@cckozie  ok so I loaded that folder and still can't reproduce it. Your call.

**Comment by cckozie** [comment]
Works in Travis build 1433 and beyond.
