### ISSUE TITLE
import studio file with merge

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2187]
Notes
======
import studio file with merge

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 175
UDID | a4b66484d349dee1
Android Release | 5.0.2
Android SDK | 21
Brand | lge
Device | e9wifi
Stack trace
======
```java
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{24bb60c1 position=14 id=-1, oldPos=14, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5251)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5433)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3488)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2102)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

```

**Comment by cckozie** [comment]
1. Imported 
[en-x-demo1_php_text_ulb-m3.tstudio.zip](https://github.com/unfoldingWord-dev/ts-android/files/936528/en-x-demo1_php_text_ulb-m3.tstudio.zip)
2. Imported selecting Merge option
[en-x-demo1_php_text_ulb-m4.tstudio.zip](https://github.com/unfoldingWord-dev/ts-android/files/936532/en-x-demo1_php_text_ulb-m4.tstudio.zip)
3. Verified conflicts as expected
4. Imported selecting merge option
[en-x-demo1_php_text_ulb-base.tstudio.zip](https://github.com/unfoldingWord-dev/ts-android/files/936541/en-x-demo1_php_text_ulb-base.tstudio.zip)
App crashed. Repeatable on my LG device.

**Comment by neutrinog** [comment]
this might be a bug in Android. Attempting a workaround.

**Comment by cckozie** [comment]
It worked!
