### ISSUE TITLE
OBS test 3

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2218]
Notes
======
OBS test 3

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 175
UDID | b65ef2f052953fdb
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Log history
======
```java
4/24/17 12:06 PM  E/com.door43.translationstudio.tasks.PullTargetTranslationTask: git@git.door43.org:qa99/en_obs_text_obs.git: Auth fail
org.eclipse.jgit.api.errors.TransportException: git@git.door43.org:qa99/en_obs_text_obs.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:261)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.pull(PullTargetTranslationTask.java:148)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.start(PullTargetTranslationTask.java:82)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.TransportException: git@git.door43.org:qa99/en_obs_text_obs.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 7 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 14 more

     

```

**Comment by cckozie** [comment]
This time I deleted the log before running the test.

**Comment by neutrinog** [comment]
this is super bizarre. I did not expect to the Auth exception here. This is going to be more difficult to debug than I thought.

**Comment by neutrinog** [comment]
This project keeps getting reverted back to the original in the app when uploading. 
https://git.door43.org/qa99/en_obs_text_obs/commit/20941e49211b567e1fcf660363df1770a66f5ebf

**Comment by neutrinog** [comment]
ok I figured out it was using the wrong merge strategy in a small corner case.
