### ISSUE TITLE
I merged two projects then selected one of the t...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2222]
Notes
======
I merged two projects then selected one of the text options in a chunk and clicked confirm

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 175
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Stack trace
======
```java
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{38bf364d position=2 id=-1, oldPos=-1, pLpos:-1 no parent}
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5251)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5433)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
	at android.support.v7.widget.LinearLayoutManager.onFocusSearchFailed(LinearLayoutManager.java:1925)
	at android.support.v7.widget.RecyclerView.focusSearch(RecyclerView.java:2317)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:718)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:718)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:718)
	at android.view.ViewGroup.focusSearch(ViewGroup.java:718)
	at android.view.View.focusSearch(View.java:7295)
	at android.widget.TextView.onCreateInputConnection(TextView.java:5988)
	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1181)
	at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1131)
	at android.widget.TextView.setText(TextView.java:3977)
	at android.widget.TextView.setText(TextView.java:3915)
	at android.widget.EditText.setText(EditText.java:85)
	at android.widget.TextView.setText(TextView.java:3890)
	at com.door43.translationstudio.ui.translate.ReviewModeAdapter$9$1.run(ReviewModeAdapter.java:655)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```
Log history
======
```java
4/25/17 8:09 AM  I/com.door43.translationstudio.services.BackupService: Backups running every 5 minute/s
4/25/17 8:09 AM  I/com.door43.translationstudio.services.BackupService: Backups running every 5 minute/s
4/25/17 8:09 AM  I/com.door43.translationstudio.services.BackupService: starting backup service
4/25/17 8:08 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/25/17 8:08 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/25/17 8:08 AM  I/com.door43.translationstudio.ui.home.ImportFromDoor43Dialog: Repository cloned from https://git.door43.org/qa99/en-x-demo2_php_text_reg
4/25/17 8:08 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/25/17 8:08 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/25/17 8:07 AM  I/com.door43.translationstudio.ui.home.ImportFromDoor43Dialog: Repository cloned from https://git.door43.org/qa99/en-x-demo2_php_text_reg
4/25/17 8:07 AM  I/com.door43.translationstudio.ui.home.ImportFromDoor43Dialog: Repository cloned from https://git.door43.org/qa99/en-x-demo1_php_text_reg
4/25/17 8:06 AM  I/ViewModeFragment: doScrollToPosition: position=13, offset=0
4/25/17 8:06 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/25/17 8:06 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
4/25/17 8:06 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
4/25/17 8:06 AM  I/ViewModeFragment: doScrollToPosition: position=3, offset=0
4/25/17 8:06 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/25/17 8:06 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en_tit_text_reg
4/25/17 8:06 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_psa_text_reg
4/25/17 8:06 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo2_php_text_reg
4/25/17 8:06 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en_obs_text_obs
4/25/17 8:04 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
4/25/17 8:04 AM  I/com.door43.translationstudio.services.BackupService: en_obs_text_obs backed up
4/25/17 8:04 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
4/25/17 8:03 AM  I/ViewModeFragment: doScrollToPosition: position=3, offset=0
4/25/17 8:03 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/25/17 8:03 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
4/25/17 8:03 AM  I/com.door43.translationstudio.services.BackupService: en_obs_text_obs backed up
4/25/17 8:03 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
4/25/17 8:02 AM  I/com.door43.translationstudio.ui.dialogs.BackupDialog: The server contains conflicting changes for en_obs_text_obs
4/25/17 8:02 AM  I/PullTargetTranslationTask: Reverting to local license
4/25/17 8:02 AM  I/PullTargetTranslationTask: Reverting to server manifest
4/25/17 8:01 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/25/17 8:01 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/25/17 8:01 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/25/17 8:01 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/25/17 8:00 AM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
4/25/17 8:00 AM  I/ViewModeFragment: doScrollToPosition: position=3, offset=0
4/25/17 7:59 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
     

```

**Comment by cckozie** [comment]
To replicate:
Import project https://git.door43.org/qa99/en-x-demo1_php_text_reg
Change that project's target language to English demo 2
Import project https://git.door43.org/qa99/en-x-demo2_php_text_reg choosing Merge projects option
Go to Chapter 1, chunk 1 and click on the last text option in that chunk, then Click on the Confirm button

**Comment by cckozie** [comment]
Travis build 1448
Now works on my Lenovo, LG, Chromo, Nexus, and Moto X. Can not test on my NeuTab because I can't change target languages on that device since clicking the info button crashes the app.
