### ISSUE TITLE
received an unable to import project message

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2230]
Notes
======
received an unable to import project message

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 175
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Log history
======
```java
4/27/17 8:28 AM  E/com.door43.translationstudio.ui.home.ImportFromDoor43Dialog: Failed to open the online backup
4/27/17 8:27 AM  W/com.door43.translationstudio.tasks.LoginDoor43Task: gogs api responded with 401: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/users/qa99/tokens
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createToken(GogsAPI.java:420)
	at com.door43.translationstudio.tasks.LoginDoor43Task.start(LoginDoor43Task.java:75)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

4/27/17 8:24 AM  I/com.door43.translationstudio.services.BackupService: en-x-demo2_php_text_reg backed up
4/27/17 8:24 AM  I/com.door43.translationstudio.services.BackupService: Checking for changes
4/27/17 8:24 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/27/17 8:24 AM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
4/27/17 8:23 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en_tit_text_reg
4/27/17 8:23 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo2_php_text_reg
4/27/17 8:23 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en-x-demo1_php_text_ulb
4/27/17 8:23 AM  I/UpdateAppTask: Migrating: /storage/emulated/0/translationStudio/translations/en_obs_text_obs
4/27/17 8:23 AM  I/CrashReporterActivity: UploadCrashReportTask success:true
     

```

**Comment by cckozie** [comment]
I've imported this project many times on many devices. 
I was testing issue #2222 and received a failure although it had worked on a different device. So I uninstalled tS and redownloaded and installed travis build 1444. When I attempted to import the 1st project in that issue, I got the failed to import message. I tried again with the same result.

**Comment by cckozie** [comment]
After experiencing this I removed the app, rebooted the device, redownloaded and installed the app, then ran the import again. Now the import works.

**Comment by PhotoNomad0** [comment]
@cckozie - this looks like a server issue.  They have been working on server issues lately.  They rebooted yesterday, and have been working on various issues.  There is nothing in the log that implies that it is the app that is failing.  The server is returning the 401 (not found) code.

**Comment by cckozie** [comment]
Moving to backlog.
