### ISSUE TITLE
while i was typing the program stopped. And it ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2289]
Notes
======
while i was typing the program stopped. And it stops all the time and i can not work... Very bad!

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 176
UDID | e4ed0e33b8d8cc93
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Stack trace
======
```java
java.lang.RuntimeException: Unable to resume activity {com.translationstudio.androidapp/com.door43.translationstudio.ui.translate.TargetTranslationActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@22b41e60 is not valid; is your activity running?
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3141)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@22b41e60 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:678)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:279)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
	at android.app.Dialog.show(Dialog.java:298)
	at com.door43.translationstudio.ui.translate.ViewModeFragment.showProgressDialog(ViewModeFragment.java:430)
	at com.door43.translationstudio.ui.translate.ViewModeFragment.showProgressDialog(ViewModeFragment.java:434)
	at com.door43.translationstudio.ui.translate.ViewModeFragment.onResume(ViewModeFragment.java:354)
	at com.door43.translationstudio.ui.translate.ReviewModeFragment.onResume(ReviewModeFragment.java:111)
	at android.app.Fragment.performResume(Fragment.java:2112)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:933)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1072)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1054)
	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1905)
	at android.app.Activity.performResume(Activity.java:6067)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
	... 9 more

```
Log history
======
```java
8/7/17 7:54 PM  W/ListItem: missing project translation for rmy-x-vwa_luk_text_reg
8/7/17 7:41 PM  W/ListItem: missing project translation for rmy-x-vwa_luk_text_reg
8/6/17 10:50 AM  E/TargetTranslation: Failed to stage changes for rmy-x-vwa_luk_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1051)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/rmy-x-vwa_luk_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 3 more

8/6/17 10:49 AM  W/ListItem: missing project translation for rmy-x-vwa_luk_text_reg
8/4/17 5:38 PM  W/ListItem: missing project translation for rmy-x-vwa_luk_text_reg
8/3/17 12:54 PM  W/ListItem: missing project translation for rmy-x-vwa_luk_text_reg
8/1/17 7:46 PM  W/ListItem: missing project translation for rmy-x-vwa_luk_text_reg
8/1/17 5:42 PM  W/ListItem: missing project translation for rmy-x-vwa_luk_text_reg
8/1/17 5:29 PM  W/ListItem: missing project translation for rmy-x-vwa_luk_text_reg
8/1/17 5:01 PM  W/ListItem: missing project translation for rmy-x-vwa_luk_text_reg
8/1/17 4:58 PM  W/ListItem: missing project translation for rmy-x-vwa_luk_text_reg
     

```

**Comment by jag3773** [comment]
@PhotoNomad0 Would you please review this report?
