### ISSUE TITLE
at act

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2311]
Notes
======
at act

Environment
======
Environment Key | Value
:----: | :----:
version | 9.0
build | 138
UDID | 48da7fd8bf8940a5
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Stack trace
======
```java
java.lang.ArithmeticException: divide by zero
	at com.door43.translationstudio.DeveloperToolsActivity$12.run(DeveloperToolsActivity.java:353)
	at com.door43.translationstudio.DeveloperToolsActivity$4.onItemClick(DeveloperToolsActivity.java:124)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1185)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3222)
	at android.widget.AbsListView$3.run(AbsListView.java:4138)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

```
Log history
======
```java
8/15/17 5:59 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation sgw_act_text_reg
8/15/17 5:59 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation sgw_act_text_reg
     

```

**Comment by neutrinog** [comment]
old version.
