### ISSUE TITLE
scrolling in Mark - using checking section

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2460]
Notes
======
scrolling in Mark - using checking section

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 176
UDID | 7fab646a7b0de076
Android Release | 6.0
Android SDK | 23
Brand | Lenovo
Device | TB3-X70F
Stack trace
======
```java
java.lang.RuntimeException: Unable to resume activity {com.translationstudio.androidapp/com.door43.translationstudio.ui.translate.TargetTranslationActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@7f2098e is not valid; is your activity running?
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3325)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3356)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1543)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5765)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@7f2098e is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:683)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:319)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.app.Dialog.show(Dialog.java:326)
	at com.door43.translationstudio.ui.translate.ViewModeFragment.showProgressDialog(ViewModeFragment.java:430)
	at com.door43.translationstudio.ui.translate.ViewModeFragment.showProgressDialog(ViewModeFragment.java:434)
	at com.door43.translationstudio.ui.translate.ViewModeFragment.onResume(ViewModeFragment.java:354)
	at com.door43.translationstudio.ui.translate.ReviewModeFragment.onResume(ReviewModeFragment.java:111)
	at android.app.Fragment.performResume(Fragment.java:2279)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1013)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1135)
	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1990)
	at android.app.FragmentController.dispatchResume(FragmentController.java:174)
	at android.app.Activity.performResume(Activity.java:6405)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3310)
	... 8 more

```
Log history
======
```java
3/7/18 06:10  E/com.door43.translationstudio.core.TargetTranslation: Failed to commit changes for saq_mrk_text_reg
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of commit command
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:317)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1069)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:1034)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:1108)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/saq_mrk_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:235)
	... 3 more

     

```

**Comment by mondele** [comment]
We are seeing something similar. Scrolling from Chapter 4 to Chapter 6 the app crashes. This happened in blind draft mode and in edit mode. We were able to get to Chapter 6 using read mode, and then switch to draft mode.

**Comment by jag3773** [comment]
@neutrinog Could this be related to content updates?

@mondele what source text were you using?

**Comment by mondele** [comment]
PT-br ulb

John Wood
Sent from my mobile device. Please forgive my brevity and typos/autocorrect

________________________________

**Comment by neutrinog** [comment]
It could very well be. I'll check.
