### ISSUE TITLE
crashes when receiving data from p2p server after screen goes to sleep

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#270]
Environment
======
version: 2.0.3
build: 55
UDID: e59d02e45e77051f
Android Release: 4.4.1
Androind SDK: 19
Brand: Samsung
Device: SPH-D710
Stack trace
======
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1323)
	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597)
	at android.app.BackStackRecord.commit(BackStackRecord.java:575)
	at android.app.DialogFragment.show(DialogFragment.java:247)
	at com.door43.translationstudio.device2device.DeviceToDeviceActivity.showProjectSelectionDialog(DeviceToDeviceActivity.java:1032)
	at com.door43.translationstudio.device2device.DeviceToDeviceActivity.access$800(DeviceToDeviceActivity.java:73)
	at com.door43.translationstudio.device2device.DeviceToDeviceActivity$9.run(DeviceToDeviceActivity.java:997)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5081)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
	at dalvik.system.NativeStart.main(Native Method)
Log history
======
2/6/15 4:34 PM  I/com.door43.translationstudio.projects.ProjectSharing: Missing project source for import
2/6/15 4:34 PM  I/com.door43.translationstudio.projects.ProjectSharing: Missing project source for import

**Comment by neutrinog** [comment]
This is hard to reproduce unless you are debugging the server device and pause it in the middle of the socket transaction.

**Comment by neutrinog** [comment]
we will move to a different network platform soon so this won't matter.
