### ISSUE TITLE
switched from Amharic obs sou...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#485]
Notes
======
switched from Amharic obs source to English

Environment
======
version: 2.2.0
build: 83
UDID: dd19773da22f5f
Android Release: 5.0
Androind SDK: 21
Brand: Verizon
Device: kltevzw
Stack trace
======
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.door43.translationstudio.projects.Chapter.getId()' on a null object reference
	at com.door43.translationstudio.projects.data.IndexStore.getSourceChapterDir(IndexStore.java:313)
	at com.door43.translationstudio.projects.data.IndexStore.loadFrames(IndexStore.java:195)
	at com.door43.translationstudio.tasks.LoadFramesTask.start(LoadFramesTask.java:34)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Log history
======
5/28/15 12:17 PM  E/com.door43.translationstudio.projects.ProjectManager: malformed notes for project obs
org.json.JSONException: End of input at character 0 of 
	at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
	at org.json.JSONTokener.nextValue(JSONTokener.java:97)
	at org.json.JSONArray.<init>(JSONArray.java:92)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at com.door43.translationstudio.projects.ProjectManager.loadNotes(ProjectManager.java:1327)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:179)
	at com.door43.translationstudio.tasks.IndexResourceTask.start(IndexResourceTask.java:56)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

5/28/15 12:17 PM  E/com.door43.translationstudio.projects.ProjectManager: malformed terms for project obs
org.json.JSONException: End of input at character 0 of 
	at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
	at org.json.JSONTokener.nextValue(JSONTokener.java:97)
	at org.json.JSONArray.<init>(JSONArray.java:92)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at com.door43.translationstudio.projects.ProjectManager.loadTerms(ProjectManager.java:1383)
	at com.door43.translationstudio.projects.ProjectManager.fetchProjectSource(ProjectManager.java:171)
	at com.door43.translationstudio.tasks.IndexResourceTask.start(IndexResourceTask.java:56)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

5/25/15 7:30 AM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
5/25/15 7:30 AM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
5/25/15 7:30 AM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
5/25/15 7:30 AM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
5/25/15 7:30 AM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
5/25/15 7:30 AM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
5/24/15 8:39 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
5/24/15 8:39 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
5/24/15 8:39 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
5/24/15 8:39 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames

**Comment by neutrinog** [comment]
@jag3773 I think this is your device. I can't reproduce this.
