### ISSUE TITLE
upload failed but not really

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#496]
Notes
======
upload failed but not really

Environment
======
version: 2.2.0
build: 84
UDID: dd19773da22f5f
Android Release: 5.0
Androind SDK: 21
Brand: Verizon
Device: kltevzw
Log history
======
6/21/15 3:00 PM  E/com.door43.translationstudio.tasks.UploadProjectTask: Project upload exception
org.eclipse.jgit.api.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
	at com.door43.translationstudio.tasks.UploadProjectTask.pushRepo(UploadProjectTask.java:234)
	at com.door43.translationstudio.tasks.UploadProjectTask.pushProject(UploadProjectTask.java:209)
	at com.door43.translationstudio.tasks.UploadProjectTask.start(UploadProjectTask.java:142)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1174)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
	... 7 more

6/21/15 2:59 PM  E/com.door43.translationstudio.tasks.UploadProjectTask: Project upload exception
org.eclipse.jgit.api.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
	at com.door43.translationstudio.tasks.UploadProjectTask.pushRepo(UploadProjectTask.java:234)
	at com.door43.translationstudio.tasks.UploadProjectTask.pushProject(UploadProjectTask.java:209)
	at com.door43.translationstudio.tasks.UploadProjectTask.start(UploadProjectTask.java:142)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1174)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
	... 7 more

6/21/15 2:56 PM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.10
6/18/15 10:47 AM  E/com.door43.translationstudio.projects.Project: failed to fetch the git commit
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.projects.Project.getLocalTranslationVersion(Project.java:821)
	at com.door43.translationstudio.projects.Project.getLocalTranslationVersion(Project.java:845)
	at com.door43.translationstudio.projects.Sharing.exportDW(Sharing.java:1039)
	at com.door43.translationstudio.SharingActivity$3$1.run(SharingActivity.java:147)
	at com.door43.util.threads.ThreadableUI$1.run(ThreadableUI.java:27)

6/1/15 9:40 AM  W/com.door43.translationstudio.panes.right.tabs.TermsTabFragment: unknown term christ
6/1/15 9:37 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
6/1/15 9:34 AM  W/com.door43.translationstudio.panes.right.tabs.TermsTabFragment: unknown term christ
6/1/15 9:34 AM  W/com.door43.translationstudio.panes.right.tabs.TermsTabFragment: unknown term christ
6/1/15 9:33 AM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
5/31/15 1:48 PM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.9

**Comment by jag3773** [comment]
If you upload an already uploaded and unchanged translation, git replies with 'nothing to push', which is interpreted as an upload fail.  Really this should be on OK.
