### ISSUE TITLE
after backup I got a success ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#497]
Notes
======
after backup I got a success dialog box that said 'upload failed' in it.

Environment
======
version: 2.2.0
build: 84
UDID: dd19773da22f5f
Android Release: 5.0
Androind SDK: 21
Brand: Verizon
Device: kltevzw
Log history
======
6/21/15 3:01 PM  E/com.door43.translationstudio.tasks.UploadProjectTask: Project upload exception
org.eclipse.jgit.api.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
	at com.door43.translationstudio.tasks.UploadProjectTask.pushRepo(UploadProjectTask.java:234)
	at com.door43.translationstudio.tasks.UploadProjectTask.pushProject(UploadProjectTask.java:209)
	at com.door43.translationstudio.tasks.UploadProjectTask.start(UploadProjectTask.java:142)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1174)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
	... 7 more

6/21/15 3:01 PM  E/com.door43.translationstudio.tasks.UploadProjectTask: Project upload exception
org.eclipse.jgit.api.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
	at com.door43.translationstudio.tasks.UploadProjectTask.pushRepo(UploadProjectTask.java:234)
	at com.door43.translationstudio.tasks.UploadProjectTask.pushProject(UploadProjectTask.java:209)
	at com.door43.translationstudio.tasks.UploadProjectTask.start(UploadProjectTask.java:142)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1174)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
	... 7 more

**Comment by neutrinog** [comment]
this is due to the profile getting pushed.
