### ISSUE TITLE
some of the descriptions in t...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#510]
Notes
======
some of the descriptions in the frames list for obs are squished to the left.

Environment
======
version: 2.2.0
build: 86
UDID: 7792b4f461ec9d4f
Android Release: 4.4.4
Androind SDK: 19
Brand: Lenovo
Device: A10-70F
Log history
======
7/2/15 2:05 AM  E/com.door43.translationstudio.util.AppContext: Could not load the typeface GentiumPlus.ttf
java.lang.RuntimeException: native typeface cannot be made
	at android.graphics.Typeface.<init>(Typeface.java:175)
	at android.graphics.Typeface.createFromFile(Typeface.java:159)
	at com.door43.translationstudio.util.AppContext.graphiteTypeface(AppContext.java:190)
	at com.door43.translationstudio.tasks.LoadModelFontTask.start(LoadModelFontTask.java:29)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:848)

**Comment by neutrinog** [comment]
https://github.com/unfoldingWord-dev/ts-android/issues/512
