### ISSUE TITLE
was trying to import from multipletablets and t...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#603]
Notes
======
was trying to import from multipletablets and thiserror occured

Environment
======
Environment Key | Value
:----: | :----:
version | 2.2.1
build | 87
UDID | 60293ed0efe93097
Android Release | 4.4.2
Android SDK | 19
Brand | hp
Device | maple
Stack trace
======
```java
java.lang.NullPointerException
	at android.app.DialogFragment.onActivityCreated(DialogFragment.java:469)
	at android.app.Fragment.performActivityCreated(Fragment.java:1708)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:908)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
	at android.app.BackStackRecord.run(BackStackRecord.java:684)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5017)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)

```
Log history
======
```java
8/6/15 11:24 AM  E/com.door43.translationstudio.migration.UpdateManager: The database from version 1.x could not be found at /data/data/com.translationstudio.androidapp/app_webview/databases/file__0/1
     
```

**Comment by neutrinog** [comment]
fixed in 2.3
