### ISSUE TITLE
Starting new project

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#780]
Notes
======
Starting new project

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 98
UDID | 1b382861d3bfe256
Android Release | 4.4.2
Android SDK | 19
Brand | generic_x86
Device | generic_x86
Stack trace
======
```java
java.lang.NullPointerException
	at com.door43.translationstudio.core.Library.getProjectCategories(Library.java:367)
	at com.door43.translationstudio.newui.newtranslation.ProjectListFragment$1.onItemClick(ProjectListFragment.java:46)
	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2904)
	at android.widget.AbsListView$3.run(AbsListView.java:3638)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5017)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)

```
Log history
======
```java
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for jer
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for php
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for job
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 2ki
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for luk
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 2jn
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for est
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for ezk
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for jas
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for zec
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for oba
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 1ch
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for lev
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for jon
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for nam
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for heb
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for obs
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for mic
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for eph
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for exo
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for hos
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for rut
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for col
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 2pe
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for rev
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for jhn
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for gen
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 3jn
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for jud
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for deu
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for pro
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 2th
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 1sa
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for jol
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for dan
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 1co
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 2co
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for jos
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for amo
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 2ti
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 2sa
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for hag
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for ezr
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for psa
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for isa
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for mal
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for jdg
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for ecc
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for neh
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for mat
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for gal
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for num
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 1ti
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 1pe
9/24/15 4:28 PM  W/com.door43.translationstudio.core.Library: Could not find any source languages for 1ki
9/24/15 4:27 PM  E/com.door43.translationstudio.MainApplication: non-critical exception
java.io.IOException: open failed: ENOENT (No such file or directory)
	at java.io.File.createNewFile(File.java:946)
	at com.door43.translationstudio.MainApplication.generateKeys(MainApplication.java:435)
	at com.door43.translationstudio.SplashScreenActivity.onFinished(SplashScreenActivity.java:147)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
	at java.io.File.createNewFile(File.java:939)
	... 6 more

9/24/15 4:27 PM  E/com.door43.translationstudio.core.Library: Failed to deploy the library
java.io.IOException: write failed: ENOSPC (No space left on device)
	at libcore.io.IoBridge.write(IoBridge.java:455)
	at java.io.FileOutputStream.write(FileOutputStream.java:187)
	at com.door43.util.Zip.unzip(Zip.java:314)
	at com.door43.translationstudio.core.Library.deployDefaultLibrary(Library.java:71)
	at com.door43.translationstudio.tasks.InitializeLibraryTask.start(InitializeLibraryTask.java:18)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: libcore.io.ErrnoException: write failed: ENOSPC (No space left on device)
	at libcore.io.Posix.writeBytes(Native Method)
	at libcore.io.Posix.write(Posix.java:202)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:197)
	at libcore.io.IoBridge.write(IoBridge.java:450)
	... 8 more

     
```

**Comment by jag3773** [comment]
This is a crash from my emulator, I went to new project > Afaraf > Bible: OT and got the crash.

Note that OBS was not in the project list.

**Comment by neutrinog** [comment]
yeah this is an issue with the enormous disk space requirement. `No space left on device`.

**Comment by neutrinog** [comment]
related to https://github.com/unfoldingWord-dev/ts-android/issues/689
