### ISSUE TITLE
tried to update library

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#796]
Notes
======
tried to update library

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 100
UDID | dd19773da22f5f
Android Release | 5.0
Android SDK | 21
Brand | Verizon
Device | kltevzw
Stack trace
======
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.translationstudio.androidapp/com.door43.translationstudio.newui.library.ProjectLibraryDetailActivity}: java.lang.ClassCastException: com.door43.translationstudio.newui.library.ProjectLibraryDetailActivity@25665477 must implement OnEventListener
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.access$900(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.ClassCastException: com.door43.translationstudio.newui.library.ProjectLibraryDetailActivity@25665477 must implement OnEventListener
	at com.door43.translationstudio.newui.library.ServerLibraryDetailFragment.onAttach(ServerLibraryDetailFragment.java:331)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:858)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
	at android.app.BackStackRecord.run(BackStackRecord.java:833)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
	at android.app.Activity.performStart(Activity.java:6257)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2624)
	... 10 more

```

**Comment by neutrinog** [comment]
This on on a phone. We need to finish phone support.

**Comment by neutrinog** [comment]
related to #798
