### ISSUE TITLE
Mode Icon Highlighting

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#797]
Notes
======
highlighting of viewing modes

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 100
UDID | bd49ee6d9a9447ed
Android Release | 5.1
Android SDK | 22
Brand | google
Device | flo
Log history
======
```java
9/29/15 3:55 PM  E/com.door43.translationstudio.service.BackupService: Failed to read commit hash
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.core.TargetTranslation.commitHash(TargetTranslation.java:390)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:120)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:44)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:76)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

9/29/15 3:55 PM  W/com.door43.translationstudio.service.BackupService: Failed to export the target translation: uw-obs-aa
9/29/15 3:46 PM  W/com.door43.translationstudio.service.BackupService: Failed to export the target translation: uw-obs-aa
9/29/15 3:40 PM  W/com.door43.translationstudio.service.BackupService: Failed to export the target translation: uw-obs-aa
9/29/15 3:35 PM  W/com.door43.translationstudio.service.BackupService: Failed to export the target translation: uw-obs-aa
9/29/15 3:30 PM  W/com.door43.translationstudio.service.BackupService: Failed to export the target translation: uw-obs-aa
9/29/15 3:24 PM  W/com.door43.translationstudio.service.BackupService: Failed to export the target translation: uw-obs-aa
9/29/15 3:19 PM  W/com.door43.translationstudio.service.BackupService: Failed to export the target translation: uw-obs-aa
9/29/15 3:14 PM  W/com.door43.translationstudio.service.BackupService: Failed to export the target translation: uw-obs-aa
9/29/15 3:09 PM  E/com.door43.translationstudio.service.BackupService: Failed to read commit hash
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.core.TargetTranslation.commitHash(TargetTranslation.java:390)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:120)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:44)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:76)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

     
```

**Comment by jag3773** [comment]
The mode that the user is on looses it's highlight occasionally, I think that is viewable in https://free.testfairy.com/projects/1370638-translationstudio/builds/1866438/sessions/10.

I can verify that this happens when rotating the device as well.
