### ISSUE TITLE
Dragging a verse-number to its correct spot in ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#868]
Notes
======
Dragging a verse-number to its correct spot in the verse after I accidentally dropped it in the middle of a word.

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 104
UDID | 8e3f7094b4ee6086
Android Release | 4.0.3
Android SDK | 15
Brand | asus
Device | TF101
Stack trace
======
```java
java.lang.IndexOutOfBoundsException: getChars (0 ... 247) ends beyond length 245
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:945)
	at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:839)
	at android.text.TextUtils.getChars(TextUtils.java:70)
	at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:58)
	at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:831)
	at com.door43.translationstudio.newui.translate.ReviewModeAdapter$16$1.onDrag(ReviewModeAdapter.java:722)
	at android.view.View.dispatchDragEvent(View.java:13466)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1186)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1030)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:3471)
	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2620)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4424)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
	at dalvik.system.NativeStart.main(Native Method)

```
Log history
======
```java
10/8/15 5:07 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 5:07 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 5:06 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 5:03 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 5:03 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:49 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:49 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:48 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:48 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:47 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:42 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:22 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:22 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:09 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:07 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:06 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord seed in gen-en-ulb
10/8/15 4:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord fruit in gen-en-ulb
10/8/15 4:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:02 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:01 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:00 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:00 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 4:00 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:59 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:59 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:58 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:58 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:56 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:56 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:56 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:55 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:50 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:50 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:50 AM  E/com.door43.translationstudio.service.BackupService: Failed to export the target translation uw-gen-nl
java.io.FileNotFoundException: /data/data/com.translationstudio.androidapp/files/translations/uw-gen-nl/.git/index.lock: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:406)
	at java.io.FileInputStream.<init>(FileInputStream.java:78)
	at java.io.FileInputStream.<init>(FileInputStream.java:105)
	at com.door43.util.Zip.zipSubFolder(Zip.java:208)
	at com.door43.util.Zip.zipSubFolder(Zip.java:203)
	at com.door43.util.Zip.zip(Zip.java:133)
	at com.door43.translationstudio.core.Translator.export(Translator.java:208)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:128)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:34)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:66)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
	at libcore.io.IoBridge.open(IoBridge.java:390)
	... 10 more

10/8/15 3:50 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:45 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:45 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:44 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:40 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:36 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:36 AM  W/com.door43.translationstudio.newui.translate.ReviewModeFragment: The gesture dectector was not initialized so the touch was not handled
10/8/15 3:36 AM  W/com.door43.translationstudio.newui.translate.ReviewModeFragment: The gesture dectector was not initialized so the touch was not handled
10/8/15 3:36 AM  W/com.door43.translationstudio.newui.translate.ReadModeFragment: The gesture dectector was not initialized so the touch was not handled
10/8/15 3:36 AM  W/com.door43.translationstudio.newui.translate.ReadModeFragment: The gesture dectector was not initialized so the touch was not handled
10/8/15 3:33 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:32 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
10/8/15 3:31 AM  W/com.door43.translationstudio.service.BackupService: Failed to read commit hash
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.core.TargetTranslation.commitHash(TargetTranslation.java:499)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:110)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:34)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:66)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

10/8/15 3:31 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord good in gen-en-ulb
     
```

**Comment by neutrinog** [comment]
I'm not sure what's happening here. I haven't taken the time to try replicating this yet.

**Comment by neutrinog** [comment]
@jshuma I just pushed some updates involving the verse markers. Make sure to get those to avoid merge conflicts.

**Comment by jshuma** [comment]
I can't seem to reproduce this. It seems to originate from a call to `subSequence()` in `onDrag()`; all calls to that in the current code come from pulling text offsets from the drag event, or from the pin. The only way I could see this exception being thrown would be if one of these gets out of sync with the actual text, either because the text changed between the beginning and end of the drop event (which isn't possible as far as I know) or because the pin/event don't match the text in the drag target, such as when dragging a verse marker to a different frame -- and, back when this was possible, I definitely saw instances of the text getting mangled in unexpected ways when doing this (even though I didn't see this particular crash). Now that issue #826 is fixed, I think that shouldn't be possible anymore.

**Comment by neutrinog** [comment]
ok let's close this for now. if the issues comes up again we'll get another bug report! :)
