### ISSUE TITLE
Text Search Feature

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#882]
Would be nice to be able to search through the source or the target text.

**Comment by neutrinog** [comment]
@jag3773  Could we place a search button in the menu? When clicked we could display a search bar above the cards where they can begin typing to filter the cards.

**Comment by neutrinog** [comment]
@PhotoNomad0 I think we can just display a search button (with magnifying glass icon) in the menu while in the translate activity. We need to mock up a ui for searching both the source and the target translation, but for now let's just implement searching the source text.

Clicking on the search button can display an input field above the list of cards where the user can type in their search query. The search should automatically run after 1 second of inactivity in the input.

For starters we can filter out cards that do not contain the query text. See the `TargetLanguageAdapter` for an example Filter implementation.

**Comment by PhotoNomad0** [comment]
@neutrinog - OK have the basic source search working in review mode.  Next will add search support to chunk and read modes.  For now will put in a toggle for source and target search.

**Comment by PhotoNomad0** [comment]
@neutrinog - think I found the issue you mentioned with lots of source files changed.  I had mistakenly made a pull request against the master branch instead of develop.  Big mistake that I corrected after the fact.  You probably looked at the mistaken pull request before I corrected it.

**Comment by cckozie** [comment]
@PhotoNomad0 In testing the Search Target feature while in blind drafting mode, I was initially a little confused since I didn't see the highlighted word I was searching for. Eventually I figured out that was because the source text was on the display, not the target. I contacted Christine to get her input about whether or not users would be confused and suggested 3 possible options:
1. Leave it as is
2. Automatically display the target card on chunks where the text is found
3. Only display the search option when in review mode.
She also believed that what I saw might be confusing to our users, and suggested that only being able to search in review mode was probably quite sufficient. So at least for the time being, we'd like you to display the search icon only when in review mode.

Also, when the user clicks the search icon can you automatically set focus to the search input field?

**Comment by PhotoNomad0** [comment]
@cckozie  - I think I'll do option 3 - less confusion overall.  Will look at setting focus. @neutrinog

**Comment by neutrinog** [comment]
@cckozie @PhotoNomad0 I noticed a crash in slack that seems to be related to this feature. I pulled the crash log from testfairy for reference:

```
java.lang.ClassCastException: com.door43.translationstudio.newui.translate.FirstTabFragment cannot be cast to com.door43.translationstudio.newui.translate.ViewModeFragment
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.isSearchSupported(TargetTranslationActivity.java:366)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity$6.onClick(TargetTranslationActivity.java:273)
	at android.view.View.performClick(View.java:4780)
	at android.view.View$PerformClick.run(View.java:19866)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by PhotoNomad0** [comment]
@neutrinog - yes I have seen that also.  Have made change to check that it is instanceof.

**Comment by cckozie** [comment]
The search function as implemented works well. After reviewing it with Christine, she came up with some good suggestions for enhancing it. I will mark this as QA Passed and create a new issue for those enhancements.

**Comment by cckozie** [comment]
I have a Philippians project open, and I searched for the text "the". The results were shown as expected. When I close the search bar, the found text remains highlighted in the chunks currently on the display. In the other chunks it is not highlighted.
If I scroll down when the search is active, then it looks like the text remains highlighted in all of the chunks the I viewed when the search was active.

**Comment by cckozie** [comment]
I noticed that searching was case sensitive on desktop but no on Android. I pinged Christine for "user" input and she wants it to be case sensitive.
