### ISSUE TITLE
rotated device on library screen

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#892]
Notes
======
rotated device on library screen

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 104
UDID | e37c929dc01796f
Android Release | 5.0.2
Android SDK | 21
Brand | samsung
Device | gt58wifi
Stack trace
======
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:374)
	at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:369)
	at com.door43.translationstudio.core.Typography.getTypeface(Typography.java:87)
	at com.door43.translationstudio.core.Typography.formatSub(Typography.java:62)
	at com.door43.translationstudio.newui.library.ServerLibraryDetailFragment.rebuildLayout(ServerLibraryDetailFragment.java:141)
	at com.door43.translationstudio.newui.library.ServerLibraryDetailFragment$4.run(ServerLibraryDetailFragment.java:316)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6117)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

```
Log history
======
```java
10/7/15 6:57 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-udb
10/7/15 6:57 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-udb
10/7/15 6:57 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-udb
10/7/15 6:57 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-udb
10/7/15 6:57 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-udb
10/7/15 6:57 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-udb
10/7/15 6:57 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-udb
10/7/15 6:50 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-udb
10/7/15 6:50 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-udb
10/7/15 6:50 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-udb
10/7/15 6:50 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-udb
10/7/15 6:50 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-udb
10/7/15 6:50 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-udb
10/7/15 6:50 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-udb
10/7/15 6:49 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-udb
10/7/15 6:49 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-udb
10/7/15 6:49 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-udb
10/7/15 6:49 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-udb
10/7/15 6:49 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-udb
10/7/15 6:49 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-udb
10/7/15 6:49 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-udb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-udb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-udb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-udb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-udb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-udb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-udb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-udb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:48 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:47 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:46 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:46 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:46 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:46 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:46 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:46 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:46 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:44 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:44 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:44 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:44 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:44 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:44 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:44 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:41 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 6:40 PM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 7:59 AM  W/com.door43.translationstudio.service.BackupService: Failed to read commit hash
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.core.TargetTranslation.commitHash(TargetTranslation.java:499)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:110)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:34)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:66)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

10/7/15 7:59 AM  W/com.door43.translationstudio.service.BackupService: Failed to read commit hash
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.core.TargetTranslation.commitHash(TargetTranslation.java:499)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:110)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:34)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:66)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

10/7/15 7:59 AM  W/com.door43.translationstudio.service.BackupService: Failed to read commit hash
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.core.TargetTranslation.commitHash(TargetTranslation.java:499)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:110)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:34)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:66)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

10/7/15 7:59 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 7:59 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 7:59 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 7:59 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 7:59 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 7:59 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 7:59 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
10/7/15 7:05 AM  W/com.door43.translationstudio.service.BackupService: Failed to read commit hash
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.core.TargetTranslation.commitHash(TargetTranslation.java:499)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:110)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:34)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:66)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

10/7/15 7:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 7:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord resurrection in rom-en-ulb
10/7/15 7:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord sonofgod in rom-en-ulb
10/7/15 7:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord setapart in rom-en-ulb
10/7/15 7:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord prophet in rom-en-ulb
10/7/15 7:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord promise in rom-en-ulb
10/7/15 7:04 AM  E/com.door43.translationstudio.core.Library: Failed to parse the translationWord paul in rom-en-ulb
     
```

**Comment by jag3773** [comment]
Also from me.
