### ISSUE TITLE
scrolled to John 3 in udb

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#894]
Notes
======
scrolled to John 3 in udb

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 104
UDID | e37c929dc01796f
Android Release | 5.0.2
Android SDK | 21
Brand | samsung
Device | gt58wifi
Stack trace
======
```java
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.door43.translationstudio.core.Library.getFrames(Library.java:808)
	at com.door43.translationstudio.newui.translate.ReadModeAdapter.onBindViewHolder(ReadModeAdapter.java:246)
	at com.door43.translationstudio.newui.translate.ReadModeAdapter.onBindViewHolder(ReadModeAdapter.java:48)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5138)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4433)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4326)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1955)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1364)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1327)
	at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1155)
	at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1012)
	at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3777)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
	at android.view.Choreographer.doFrame(Choreographer.java:559)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6117)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

```
Log history
======
```java
10/13/15 11:24 AM  W/com.door43.translationstudio.service.BackupService: Failed to read commit hash
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:148)
	at com.door43.translationstudio.core.TargetTranslation.commitHash(TargetTranslation.java:499)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:110)
	at com.door43.translationstudio.service.BackupService.access$100(BackupService.java:34)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:66)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

     
```

**Comment by jag3773** [comment]
Dup #893
