### ISSUE TITLE
add backup to cloud

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#925]
Notes
======
Add "Upload to server" option in Backup menu

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 105
UDID | dd19773da22f5f
Android Release | 5.0
Android SDK | 21
Brand | Verizon
Device | kltevzw
Log history
======
```java
10/23/15 4:24 PM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
	at java.net.InetAddress.getLocalHost(InetAddress.java:396)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:509)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:482)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:354)
	at android.app.Activity.performDestroy(Activity.java:6451)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4096)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4127)
	at android.app.ActivityThread.access$1500(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

10/23/15 4:22 PM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
	at java.net.InetAddress.getLocalHost(InetAddress.java:396)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:509)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:482)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:354)
	at android.app.Activity.performDestroy(Activity.java:6451)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4096)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4127)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4332)
	at android.app.ActivityThread.access$1000(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

10/23/15 4:21 PM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
	at java.net.InetAddress.getLocalHost(InetAddress.java:396)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:509)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:482)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:354)
	at android.app.Activity.performDestroy(Activity.java:6451)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4096)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4127)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4332)
	at android.app.ActivityThread.access$1000(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

10/23/15 4:21 PM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
	at java.net.InetAddress.getLocalHost(InetAddress.java:396)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:509)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:482)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:354)
	at android.app.Activity.performDestroy(Activity.java:6451)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4096)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4127)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4332)
	at android.app.ActivityThread.access$1000(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

10/23/15 4:20 PM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
	at java.net.InetAddress.getLocalHost(InetAddress.java:396)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:509)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:482)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:354)
	at android.app.Activity.performDestroy(Activity.java:6451)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4096)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4127)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4332)
	at android.app.ActivityThread.access$1000(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

     
```

**Comment by jag3773** [comment]
This will provide an online backup mechanism without being confused with publish.  No profile information necessary here, just a git push up to the server.
