### ISSUE TITLE
1 John 2:24-26 has the wrong verse markers. it ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#939]
Notes
======
1 John 2:24-26 has the wrong verse markers. it has 26, 7, 8

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 105
UDID | f6b1fd4623e9d222
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Log history
======
```java
10/27/15 8:58 AM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1162)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getLocalHost(InetAddress.java:402)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:508)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:481)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:326)
	at android.app.Activity.performDestroy(Activity.java:6150)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1147)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3864)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
	at android.app.ActivityThread.access$1400(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

10/27/15 8:02 AM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1162)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getLocalHost(InetAddress.java:402)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:508)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:481)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:326)
	at android.app.Activity.performDestroy(Activity.java:6150)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1147)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3864)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
	at android.app.ActivityThread.access$1400(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

10/27/15 8:02 AM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1162)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getLocalHost(InetAddress.java:402)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:508)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:481)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:326)
	at android.app.Activity.performDestroy(Activity.java:6150)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1147)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3864)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
	at android.app.ActivityThread.access$1400(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

10/27/15 8:01 AM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1162)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getLocalHost(InetAddress.java:402)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:508)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:481)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:326)
	at android.app.Activity.performDestroy(Activity.java:6150)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1147)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3864)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
	at android.app.ActivityThread.access$1400(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

10/27/15 8:00 AM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1162)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getLocalHost(InetAddress.java:402)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:508)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:481)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:326)
	at android.app.Activity.performDestroy(Activity.java:6150)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1147)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3864)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4095)
	at android.app.ActivityThread.access$900(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

10/27/15 8:00 AM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1162)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getLocalHost(InetAddress.java:402)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:508)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:481)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:326)
	at android.app.Activity.performDestroy(Activity.java:6150)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1147)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3864)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4095)
	at android.app.ActivityThread.access$900(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

10/27/15 7:58 AM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1162)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getLocalHost(InetAddress.java:402)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:508)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:481)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:326)
	at android.app.Activity.performDestroy(Activity.java:6150)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1147)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3864)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
	at android.app.ActivityThread.access$1400(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

10/27/15 7:56 AM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1162)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getLocalHost(InetAddress.java:402)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:508)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:481)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:326)
	at android.app.Activity.performDestroy(Activity.java:6150)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1147)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3864)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
	at android.app.ActivityThread.access$1400(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

10/27/15 7:14 AM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1162)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getLocalHost(InetAddress.java:402)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:508)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:481)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:326)
	at android.app.Activity.performDestroy(Activity.java:6150)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1147)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3864)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
	at android.app.ActivityThread.access$1400(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

10/27/15 7:14 AM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1162)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getLocalHost(InetAddress.java:402)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:508)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:481)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:326)
	at android.app.Activity.performDestroy(Activity.java:6150)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1147)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3864)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
	at android.app.ActivityThread.access$1400(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

10/24/15 8:58 AM  E/com.door43.translationstudio.newui.translate.TargetTranslationActivity: Failed to commit changes before closing translation
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1162)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getLocalHost(InetAddress.java:402)
	at org.eclipse.jgit.util.SystemReader$1.getHostname(SystemReader.java:109)
	at org.eclipse.jgit.lib.UserConfig.getDefaultEmail(UserConfig.java:221)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:84)
	at org.eclipse.jgit.lib.UserConfig.<init>(UserConfig.java:52)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:56)
	at org.eclipse.jgit.lib.UserConfig$1.parse(UserConfig.java:54)
	at org.eclipse.jgit.lib.Config.get(Config.java:576)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:81)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:488)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:163)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:508)
	at com.door43.translationstudio.core.TargetTranslation.commit(TargetTranslation.java:481)
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onDestroy(TargetTranslationActivity.java:326)
	at android.app.Activity.performDestroy(Activity.java:6150)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1147)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3864)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
	at android.app.ActivityThread.access$1400(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

     
```

**Comment by neutrinog** [comment]
Actually it had the wrong text entirely. After clicking the edit button the
correct verses and text appeared.
